"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "es" | "en" | "fr" | "de" | "ru" | "zh"

interface Translations {
  [key: string]: {
    // Updated: removed it, pt, nl
    es: string
    en: string
    fr: string
    de: string
    ru: string
    zh: string
  }
}

const translations: Translations = {
  // Navigation
  "nav.home": {
    es: "Inicio",
    en: "Home",
    fr: "Accueil",
    de: "Startseite",
    ru: "Главная",
    zh: "首页",
  },
  "nav.excursions": {
    es: "Excursiones",
    en: "Excursions",
    fr: "Excursions",
    de: "Ausflüge",
    ru: "Экскурсии",
    zh: "游览",
  },
  "nav.about": {
    es: "Nosotros",
    en: "About",
    fr: "À propos",
    de: "Über uns",
    ru: "О нас",
    zh: "关于我们",
  },
  "nav.contact": {
    es: "Contacto",
    en: "Contact",
    fr: "Contact",
    de: "Kontakt",
    ru: "Контакты",
    zh: "联系",
  },
  "nav.booking": {
    es: "Reservar",
    en: "Book",
    fr: "Réserver",
    de: "Buchen",
    ru: "Забронировать",
    zh: "预订",
  },

  // Featured Dropdown & Cards
  "featured.view_all_short": {
    es: "Ver todas las excursiones",
    en: "View all excursions",
    fr: "Voir toutes les excursions",
    de: "Alle Ausflüge ansehen",
    ru: "Посмотреть все экскурсии",
    zh: "查看所有游览",
  },
  "featured.badge": {
    es: "Excursiones Destacadas",
    en: "Featured Excursions",
    fr: "Excursions en Vedette",
    de: "Empfohlene Ausflüge",
    ru: "Рекомендуемые Экскурсии",
    zh: "特色游览",
  },
  "featured.title": {
    es: "Aventuras Populares",
    en: "Popular Adventures",
    fr: "Aventures Populaires",
    de: "Beliebte Abenteuer",
    ru: "Популярные Приключения",
    zh: "热门探险",
  },
  "featured.subtitle": {
    es: "Las experiencias más reservadas por nuestros viajeros.",
    en: "The most booked experiences by our travelers.",
    fr: "Les expériences les plus réservées par nos voyageurs.",
    de: "Die von unseren Reisenden am häufigsten gebuchten Erlebnisse.",
    ru: "Самые бронируемые впечатления наших путешественников.",
    zh: "我们游客预订最多的体验。",
  },
  "featured.view_all": {
    es: "Ver Todas las Excursiones",
    en: "View All Excursions",
    fr: "Voir Toutes les Excursions",
    de: "Alle Ausflüge Ansehen",
    ru: "Посмотреть Все Экскурсии",
    zh: "查看所有游览",
  },
  "featured.per_person": {
    es: "por persona",
    en: "per person",
    fr: "par personne",
    de: "pro Person",
    ru: "на человека",
    zh: "每人",
  },

  // Gallery
  "gallery.badge": {
    es: "Galería de Fotos",
    en: "Photo Gallery",
    fr: "Galerie Photos",
    de: "Fotogalerie",
    ru: "Фотогалерея",
    zh: "照片库",
  },
  "gallery.title": {
    es: "Momentos Inolvidables en Tenerife",
    en: "Unforgettable Moments in Tenerife",
    fr: "Moments Inoubliables à Tenerife",
    de: "Unvergessliche Momente auf Teneriffa",
    ru: "Незабываемые моменты на Тенерифе",
    zh: "特内里费岛难忘时刻",
  },
  "gallery.subtitle": {
    es: "Explora nuestras aventuras a través de imágenes",
    en: "Explore our adventures through images",
    fr: "Explorez nos aventures à travers des images",
    de: "Erkunden Sie unsere Abenteuer durch Bilder",
    ru: "Исследуйте наши приключения через изображения",
    zh: "通过图片探索我们的冒险",
  },
  "gallery.view_all_photos": {
    es: "Ver todas las fotos",
    en: "View all photos",
    fr: "Voir toutes les photos",
    de: "Alle Fotos anzeigen",
    ru: "Посмотреть все фото",
    zh: "查看所有照片",
  },
  "gallery.explore_complete": {
    es: "Explora nuestra galería completa con",
    en: "Explore our complete gallery with",
    fr: "Explorez notre galerie complète avec",
    de: "Erkunde unsere komplette Galerie mit",
    ru: "Исследуйте нашу полную галерею с",
    zh: "探索我们的完整画廊",
  },
  "gallery.more_images": {
    es: "más imágenes",
    en: "more images",
    fr: "plus d'images",
    de: "weitere Bilder",
    ru: "больше изображений",
    zh: "更多图片",
  },
  "gallery.loading": {
    es: "Cargando galería...",
    en: "Loading gallery...",
    fr: "Chargement de la galerie...",
    de: "Galerie wird geladen...",
    ru: "Загрузка галереи...",
    zh: "加载画廊中...",
  },
  "gallery.instructions": {
    es: "Usa las flechas del teclado para navegar o haz clic en los botones",
    en: "Use keyboard arrows to navigate or click the buttons",
    fr: "Utilisez les flèches du clavier pour naviguer ou cliquez sur les boutons",
    de: "Verwenden Sie die Pfeiltasten zur Navigation oder klicken Sie auf die Schaltflächen",
    ru: "Используйте стрелки клавиатуры для навигации или нажмите на кнопки",
    zh: "使用键盘箭头导航或点击按钮",
  },
  "gallery.close": {
    es: "Cerrar galería",
    en: "Close gallery",
    fr: "Fermer la galerie",
    de: "Galerie schließen",
    ru: "Закрыть галерею",
    zh: "关闭画廊",
  },
  "gallery.previous": {
    es: "Imagen anterior",
    en: "Previous image",
    fr: "Image précédente",
    de: "Vorheriges Bild",
    ru: "Предыдущее изображение",
    zh: "上一张图片",
  },
  "gallery.next": {
    es: "Imagen siguiente",
    en: "Next image",
    fr: "Image suivante",
    de: "Nächstes Bild",
    ru: "Следующее изображение",
    zh: "下一张图片",
  },

  // Hero
  "hero.title": {
    es: "Descubre la Magia de Tenerife",
    en: "Discover the Magic of Tenerife",
    fr: "Découvrez la Magie de Tenerife",
    de: "Entdecke die Magie von Teneriffa",
    ru: "Откройте магию Тенерифе",
    zh: "发现特内里费的魅力",
  },
  "hero.subtitle": {
    es: "Explora paisajes volcánicos únicos, playas paradisíacas y experiencias inolvidables en la isla de la eterna primavera.",
    en: "Explore unique volcanic landscapes, paradise beaches and unforgettable experiences on the island of eternal spring.",
    fr: "Explorez des paysages volcaniques uniques, des plages paradisiaques et des expériences inoubliables sur l'île de l'éternel printemps.",
    de: "Erkunden Sie einzigartige Vulkanlandschaften, paradiesische Strände und unvergessliche Erlebnisse auf der Insel des ewigen Frühlings.",
    ru: "Исследуйте уникальные вулканические пейзажи, райские пляжи и незабываемые впечатления на острове вечной весны.",
    zh: "探索独特的火山景观、天堂般的海滩和永恒春天岛屿上的难忘体验。",
  },
  "hero.description": {
    es: "Vive aventuras inolvidables en Tenerife. Excursiones para todos los gustos.",
    en: "Live unforgettable adventures in Tenerife. Excursions for all tastes.",
    fr: "Vivez des aventures inoubliables à Tenerife. Des excursions pour tous les goûts.",
    de: "Erleben Sie unvergessliche Abenteuer auf Teneriffa. Ausflüge für jeden Geschmack.",
    ru: "Переживите незабываемые приключения на Тенерифе. Экскурсии на любой вкус.",
    zh: "在特内里费体验难忘的冒险。适合所有品味的游览。",
  },
  "hero.description2": {
    es: "Reserva ahora y explora la isla de la eterna primavera.",
    en: "Book now and explore the island of eternal spring.",
    fr: "Réservez maintenant et explorez l'île de l'éternel printemps.",
    de: "Buchen Sie jetzt und erkunden Sie die Insel des ewigen Frühlings.",
    ru: "Забронируйте сейчас и исследуйте остров вечной весны.",
    zh: "立即预订并探索永恒春天的岛屿。",
  },

  // CTA section
  "cta.ready_title": {
    es: "¿Listo para la aventura?",
    en: "Ready for adventure?",
    fr: "Prêt pour l'aventure ?",
    de: "Bereit für das Abenteuer?",
    ru: "Готовы к приключению?",
    zh: "准备好冒险了吗？",
  },
  "cta.ready_text": {
    es: "No esperes más para vivir la experiencia de tu vida. ¡Contacta con nosotros y planifiquemos juntos tu próxima gran aventura en Tenerife!",
    en: "Don't wait any longer to live the experience of a lifetime. Contact us and let's plan your next great adventure in Tenerife together!",
    fr: "N'attendez plus pour vivre l'expérience de votre vie. Contactez-nous et planifions ensemble votre prochaine grande aventure à Tenerife !",
    de: "Warten Sie nicht länger, um das Erlebnis Ihres Lebens zu machen. Kontaktieren Sie uns und lassen Sie uns gemeinsam Ihr nächstes großes Abenteuer auf Teneriffa planen!",
    ru: "Не ждите больше, чтобы пережить опыт всей своей жизни. Свяжитесь с нами, и давайте вместе спланируем ваше следующее большое приключение на Тенерифе!",
    zh: "不要再等待，体验一生难忘的经历。联系我们，让我们一起规划您在特内里费的下一次伟大冒险！",
  },
  "cta.contact_now": {
    es: "Contactar Ahora",
    en: "Contact Now",
    fr: "Contacter Maintenant",
    de: "Jetzt Kontaktieren",
    ru: "Связаться Сейчас",
    zh: "立即联系",
  },
  "cta.view_excursions": {
    es: "Ver Excursiones",
    en: "View Excursions",
    fr: "Voir les Excursions",
    de: "Ausflüge Ansehen",
    ru: "Посмотреть Экскурсии",
    zh: "查看游览",
  },
  "cta.adventure_title": {
    es: "Descubre Tenerife con nuestras",
    en: "Discover Tenerife with our",
    fr: "Découvrez Tenerife avec nos",
    de: "Entdecken Sie Teneriffa mit unseren",
    ru: "Откройте Тенерифе с нашими",
    zh: "通过我们的游览发现特内里费",
  },
  "cta.adventure_title2": {
    es: "excursiones",
    en: "excursions",
    fr: "excursions",
    de: "Ausflügen",
    ru: "экскурсиями",
    zh: "游览",
  },
  "cta.adventure_text": {
    es: "Vive experiencias inolvidables explorando la isla.",
    en: "Live unforgettable experiences exploring the island.",
    fr: "Vivez des expériences inoubliables en explorant l'île.",
    de: "Erleben Sie unvergessliche Erlebnisse bei der Erkundung der Insel.",
    ru: "Переживите незабываемые впечатления, исследуя остров.",
    zh: "在探索岛屿时体验难忘的经历。",
  },
  "cta.adventure_text2": {
    es: "¡Reserva ahora y comienza tu aventura!",
    en: "Book now and start your adventure!",
    fr: "Réservez maintenant et commencez votre aventure !",
    de: "Buchen Sie jetzt und starten Sie Ihr Abenteuer!",
    ru: "Забронируйте сейчас и начните свое приключение!",
    zh: "立即预订并开始您的冒险！",
  },
  "cta.book_now": {
    es: "Reservar ahora",
    en: "Book now",
    fr: "Réserver maintenant",
    de: "Jetzt buchen",
    ru: "Забронировать сейчас",
    zh: "立即预订",
  },
  "cta.more_info": {
    es: "Más información",
    en: "More info",
    fr: "Plus d'informations",
    de: "Mehr Informationen",
    ru: "Больше информации",
    zh: "更多信息",
  },

  // Cookies
  "cookies.title": {
    es: "Política de Cookies",
    en: "Cookies Policy",
    fr: "Politique de Cookies",
    de: "Cookie-Richtlinie",
    ru: "Политика файлов cookie",
    zh: "Cookie政策",
  },
  "cookies.description": {
    es: "Utilizamos cookies para mejorar tu experiencia en nuestra web. Al continuar navegando, aceptas nuestra política de cookies.",
    en: "We use cookies to improve your experience on our website. By continuing to browse, you accept our cookies policy.",
    fr: "Nous utilisons des cookies pour améliorer votre expérience sur notre site web. En continuant à naviguer, vous acceptez notre politique de cookies.",
    de: "Wir verwenden Cookies, um Ihre Erfahrung auf unserer Website zu verbessern. Durch das weitere Surfen akzeptieren Sie unsere Cookie-Richtlinie.",
    ru: "Мы используем файлы cookie для улучшения вашего опыта на нашем веб-сайте. Продолжая просмотр, вы принимаете нашу политику использования файлов cookie.",
    zh: "我们使用Cookie来改善您在我们网站上的体验。继续浏览即表示您接受我们的Cookie政策。",
  },
  "cookies.accept_all": {
    es: "Aceptar todas",
    en: "Accept all",
    fr: "Tout accepter",
    de: "Alle akzeptieren",
    ru: "Принять все",
    zh: "接受全部",
  },
  "cookies.necessary_only": {
    es: "Solo necesarias",
    en: "Necessary only",
    fr: "Nécessaires seulement",
    de: "Nur notwendige",
    ru: "Только необходимые",
    zh: "仅必要",
  },
  "cookies.customize": {
    es: "Personalizar",
    en: "Customize",
    fr: "Personnaliser",
    de: "Anpassen",
    ru: "Настроить",
    zh: "自定义",
  },
  "cookies.preferences_title": {
    es: "Preferencias de Cookies",
    en: "Cookie Preferences",
    fr: "Préférences de cookies",
    de: "Cookie-Einstellungen",
    ru: "Настройки файлов cookie",
    zh: "Cookie偏好设置",
  },
  "cookies.necessary": {
    es: "Cookies Necesarias",
    en: "Necessary Cookies",
    fr: "Cookies nécessaires",
    de: "Notwendige Cookies",
    ru: "Необходимые файлы cookie",
    zh: "必要的Cookie",
  },
  "cookies.necessary_desc": {
    es: "Estas cookies son esenciales para el funcionamiento del sitio.",
    en: "These cookies are essential for the site to function.",
    fr: "Ces cookies sont essentiels au fonctionnement du site.",
    de: "Diese Cookies sind für die Funktion der Seite unerlässlich.",
    ru: "Эти файлы cookie необходимы для функционирования сайта.",
    zh: "这些Cookie对于网站的运作至关重要。",
  },
  "cookies.analytics": {
    es: "Cookies de Análisis",
    en: "Analytics Cookies",
    fr: "Cookies d'analyse",
    de: "Analyse-Cookies",
    ru: "Аналитические файлы cookie",
    zh: "分析Cookie",
  },
  "cookies.analytics_desc": {
    es: "Nos ayudan a entender cómo los visitantes usan el sitio.",
    en: "Help us understand how visitors use the site.",
    fr: "Nous aident à comprendre comment les visiteurs utilisent le site.",
    de: "Helfen uns zu verstehen, wie Besucher die Seite nutzen.",
    ru: "Помогают нам понять, как посетители используют сайт.",
    zh: "帮助我们了解访问者如何使用网站。",
  },
  "cookies.functional": {
    es: "Cookies Funcionales",
    en: "Functional Cookies",
    fr: "Cookies fonctionnels",
    de: "Funktionale Cookies",
    ru: "Функциональные файлы cookie",
    zh: "功能性Cookie",
  },
  "cookies.functional_desc": {
    es: "Permiten recordar tus preferencias y personalizar tu experiencia.",
    en: "Allow remembering your preferences and personalizing your experience.",
    fr: "Permettent de mémoriser vos préférences et de personnaliser votre expérience.",
    de: "Ermöglichen das Speichern Ihrer Präferenzen und die Personalisierung Ihrer Erfahrung.",
    ru: "Позволяют запоминать ваши предпочтения и персонализировать ваш опыт.",
    zh: "允许记住您的偏好并个性化您的体验。",
  },
  "cookies.save_preferences": {
    es: "Guardar Preferencias",
    en: "Save Preferences",
    fr: "Enregistrer les préférences",
    de: "Einstellungen speichern",
    ru: "Сохранить настройки",
    zh: "保存偏好设置",
  },
  "cookies.more_info": {
    es: "Más información en nuestra",
    en: "More information in our",
    fr: "Plus d'informations dans notre",
    de: "Weitere Informationen in unserer",
    ru: "Больше информации в нашей",
    zh: "更多信息请参阅我们的",
  },
  "cookies.privacy_policy": {
    es: "Política de Privacidad",
    en: "Privacy Policy",
    fr: "Politique de Confidentialité",
    de: "Datenschutzrichtlinie",
    ru: "Политика конфиденциальности",
    zh: "隐私政策",
  },
  "cookies.close": {
    es: "Cerrar",
    en: "Close",
    fr: "Fermer",
    de: "Schließen",
    ru: "Закрыть",
    zh: "关闭",
  },

  // Footer
  "footer.title": {
    es: "TenerifeParadise Tours",
    en: "TenerifeParadise Tours",
    fr: "TenerifeParadise Tours",
    de: "TenerifeParadise Tours",
    ru: "TenerifeParadise Tours",
    zh: "TenerifeParadise Tours",
  },
  "footer.subtitle": {
    es: "Tours & Excursiones",
    en: "Tours & Excursions",
    fr: "Tours & Excursions",
    de: "Touren & Ausflüge",
    ru: "Туры и экскурсии",
    zh: "旅游和游览",
  },
  "footer.description": {
    es: "Descubre la magia de Tenerife con nuestras excursiones únicas. Experiencias inolvidables en la isla de la eterna primavera.",
    en: "Discover the magic of Tenerife with our unique excursions. Unforgettable experiences on the island of eternal spring.",
    fr: "Découvrez la magie de Tenerife avec nos excursions uniques. Des expériences inoubliables sur l'île de l'éternel printemps.",
    de: "Entdecken Sie die Magie Teneriffas mit unseren einzigartigen Ausflügen. Unvergessliche Erlebnisse auf der Insel des ewigen Frühlings.",
    ru: "Откройте магию Тенерифе с нашими уникальными экскурсиями. Незабываемые впечатления на острове вечной весны.",
    zh: "通过我们独特的游览发现特内里费的魅力。在永恒春天的岛屿上获得难忘的体验。",
  },
  "footer.quick_links": {
    es: "Enlaces Rápidos",
    en: "Quick Links",
    fr: "Liens Rapides",
    de: "Schnelllinks",
    ru: "Быстрые ссылки",
    zh: "快速链接",
  },
  "footer.contact_info": {
    es: "Información de Contacto",
    en: "Contact Info",
    fr: "Coordonnées",
    de: "Kontaktinformationen",
    ru: "Контактная информация",
    zh: "联系信息",
  },
  "footer.email": {
    es: "Correo",
    en: "Email",
    fr: "Email",
    de: "E-Mail",
    ru: "Эл. почта",
    zh: "电子邮件",
  },
  "footer.newsletter": {
    es: "Boletín Informativo",
    en: "Newsletter",
    fr: "Bulletin d'information",
    de: "Newsletter",
    ru: "Рассылка",
    zh: "新闻通讯",
  },
  "footer.newsletter_text": {
    es: "Suscríbete para recibir ofertas especiales y novedades sobre nuestras excursiones.",
    en: "Subscribe to receive special offers and news about our excursions.",
    fr: "Abonnez-vous pour recevoir des offres spéciales et des nouvelles sur nos excursions.",
    de: "Abonnieren Sie, um Sonderangebote und Neuigkeiten über unsere Ausflüge zu erhalten.",
    ru: "Подпишитесь, чтобы получать специальные предложения и новости о наших экскурсиях.",
    zh: "订阅以接收有关我们游览的特别优惠和新闻。",
  },
  "footer.email_placeholder": {
    es: "tu@email.com",
    en: "your@email.com",
    fr: "votre@email.com",
    de: "ihre@email.com",
    ru: "ваш@email.com",
    zh: "您的@email.com",
  },
  "footer.subscribe": {
    es: "Suscribirse",
    en: "Subscribe",
    fr: "S'abonner",
    de: "Abonnieren",
    ru: "Подписаться",
    zh: "订阅",
  },
  "footer.subscribe_success": {
    es: "¡Gracias por suscribirte a nuestro boletín!",
    en: "Thank you for subscribing to our newsletter!",
    fr: "Merci de vous être abonné à notre newsletter !",
    de: "Vielen Dank für Ihr Abonnement unseres Newsletters!",
    ru: "Спасибо за подписку на нашу рассылку!",
    zh: "感谢您订阅我们的新闻通讯！",
  },
  "footer.rights": {
    es: "Todos los derechos reservados.",
    en: "All rights reserved.",
    fr: "Tous droits réservés.",
    de: "Alle Rechte vorbehalten.",
    ru: "Все права защищены.",
    zh: "保留所有权利。",
  },
  "footer.designed_by": {
    es: "Diseñado por",
    en: "Designed by",
    fr: "Conçu par",
    de: "Entworfen von",
    ru: "Разработано",
    zh: "设计者",
  },
  "footer.privacy": {
    es: "Política de Privacidad",
    en: "Privacy Policy",
    fr: "Politique de Confidentialité",
    de: "Datenschutzrichtlinie",
    ru: "Политика конфиденциальности",
    zh: "隐私政策",
  },
  "footer.terms": {
    es: "Términos y Condiciones",
    en: "Terms & Conditions",
    fr: "Termes et Conditions",
    de: "Allgemeine Geschäftsbedingungen",
    ru: "Условия использования",
    zh: "条款和条件",
  },
  "footer.faq": {
    es: "Preguntas Frecuentes",
    en: "FAQ",
    fr: "FAQ",
    de: "FAQ",
    ru: "Часто задаваемые вопросы",
    zh: "常见问题",
  },

  // Privacy Policy Modal
  "privacy.policy.title": {
    es: "Política de Privacidad",
    en: "Privacy Policy",
    fr: "Politique de Confidentialité",
    de: "Datenschutzrichtlinie",
    ru: "Политика конфиденциальности",
    zh: "隐私政策",
  },
  "privacy.policy.subtitle": {
    es: "Última actualización: Enero 2024",
    en: "Last updated: January 2024",
    fr: "Dernière mise à jour : Janvier 2024",
    de: "Zuletzt aktualisiert: Januar 2024",
    ru: "Последнее обновление: Январь 2024",
    zh: "最后更新：2024年1月",
  },
  "privacy.policy.intro.title": {
    es: "Compromiso con tu Privacidad",
    en: "Our Privacy Commitment",
    fr: "Notre Engagement de Confidentialité",
    de: "Unser Datenschutzversprechen",
    ru: "Наши обязательства по конфиденциальности",
    zh: "我们的隐私承诺",
  },
  "privacy.policy.intro.content": {
    es: "En Tenerife Paradise Tour & Excursion, nos comprometemos a proteger y respetar tu privacidad. Esta política explica cómo recopilamos, usamos y protegemos tu información personal cuando utilizas nuestros servicios.",
    en: "At Tenerife Paradise Tour & Excursion, we are committed to protecting and respecting your privacy. This policy explains how we collect, use and protect your personal information when you use our services.",
    fr: "Chez Tenerife Paradise Tour & Excursion, nous nous engageons à protéger et respecter votre vie privée. Cette politique explique comment nous collectons, utilisons et protégeons vos informations personnelles lorsque vous utilisez nos services.",
    de: "Bei Tenerife Paradise Tour & Excursion verpflichten wir uns, Ihre Privatsphäre zu schützen und zu respektieren. Diese Richtlinie erläutert, wie wir Ihre personenbezogenen Daten erfassen, verwenden und schützen, wenn Sie unsere Dienste nutzen.",
    ru: "В Tenerife Paradise Tour & Excursion мы обязуемся защищать и уважать вашу конфиденциальность. Эта политика объясняет, как мы собираем, используем и защищаем вашу личную информацию, когда вы пользуетесь нашими услугами.",
    zh: "在Tenerife Paradise Tour & Excursion，我们致力于保护和尊重您的隐私。本政策解释了当您使用我们的服务时，我们如何收集、使用和保护您的个人信息。",
  },
  "privacy.policy.buttons.understood": {
    es: "Entendido",
    en: "Understood",
    fr: "Compris",
    de: "Verstanden",
    ru: "Понятно",
    zh: "已了解",
  },
  "privacy.policy.buttons.print": {
    es: "Imprimir",
    en: "Print",
    fr: "Imprimer",
    de: "Drucken",
    ru: "Печать",
    zh: "打印",
  },

  // Terms and Conditions Modal
  "terms.conditions.title": {
    es: "Términos y Condiciones",
    en: "Terms and Conditions",
    fr: "Termes et Conditions",
    de: "Allgemeine Geschäftsbedingungen",
    ru: "Условия и положения",
    zh: "条款和条件",
  },
  "terms.conditions.subtitle": {
    es: "Condiciones generales de contratación",
    en: "General terms of service",
    fr: "Conditions générales de service",
    de: "Allgemeine Servicebedingungen",
    ru: "Общие условия обслуживания",
    zh: "一般服务条款",
  },
  "terms.conditions.buttons.accept": {
    es: "Acepto los Términos",
    en: "Accept Terms",
    fr: "Accepter les Termes",
    de: "Bedingungen akzeptieren",
    ru: "Принять условия",
    zh: "接受条款",
  },
  "terms.conditions.buttons.print": {
    es: "Imprimir",
    en: "Print",
    fr: "Imprimer",
    de: "Drucken",
    ru: "Печать",
    zh: "打印",
  },

  // FAQ Modal
  "faq.modal.title": {
    es: "Preguntas Frecuentes",
    en: "Frequently Asked Questions",
    fr: "Questions Fréquemment Posées",
    de: "Häufig Gestellte Fragen",
    ru: "Часто Задаваемые Вопросы",
    zh: "常见问题",
  },
  "faq.modal.buttons.close": {
    es: "Cerrar",
    en: "Close",
    fr: "Fermer",
    de: "Schließen",
    ru: "Закрыть",
    zh: "关闭",
  },

  // Common
  "common.loading": {
    es: "Cargando...",
    en: "Loading...",
    fr: "Chargement...",
    de: "Laden...",
    ru: "Загрузка...",
    zh: "加载中...",
  },
  "common.loading_experiences": {
    es: "Cargando experiencias...",
    en: "Loading experiences...",
    fr: "Chargement des expériences...",
    de: "Erlebnisse werden geladen...",
    ru: "Загрузка впечатлений...",
    zh: "加载体验中...",
  },
  "common.all_ratings": {
    es: "Valoraciones de clientes",
    en: "Customer ratings",
    fr: "Évaluations des clients",
    de: "Kundenbewertungen",
    ru: "Отзывы клиентов",
    zh: "客户评分",
  },
  "common.error": {
    es: "Error",
    en: "Error",
    fr: "Erreur",
    de: "Fehler",
    ru: "Ошибка",
    zh: "错误",
  },
  "common.success": {
    es: "Éxito",
    en: "Success",
    fr: "Succès",
    de: "Erfolg",
    ru: "Успех",
    zh: "成功",
  },
  "common.close": {
    es: "Cerrar",
    en: "Close",
    fr: "Fermer",
    de: "Schließen",
    ru: "Закрыть",
    zh: "关闭",
  },
  "common.back": {
    es: "Atrás",
    en: "Back",
    fr: "Retour",
    de: "Zurück",
    ru: "Назад",
    zh: "返回",
  },
  "common.next": {
    es: "Siguiente",
    en: "Next",
    fr: "Suivant",
    de: "Weiter",
    ru: "Далее",
    zh: "下一步",
  },
  "common.previous": {
    es: "Anterior",
    en: "Previous",
    fr: "Précédent",
    de: "Vorherige",
    ru: "Предыдущий",
    zh: "上一步",
  },
  "common.save": {
    es: "Guardar",
    en: "Save",
    fr: "Enregistrer",
    de: "Speichern",
    ru: "Сохранить",
    zh: "保存",
  },
  "common.cancel": {
    es: "Cancelar",
    en: "Cancel",
    fr: "Annuler",
    de: "Abbrechen",
    ru: "Отмена",
    zh: "取消",
  },
  "common.confirm": {
    es: "Confirmar",
    en: "Confirm",
    fr: "Confirmer",
    de: "Bestätigen",
    ru: "Подтвердить",
    zh: "确认",
  },
  "common.delete": {
    es: "Eliminar",
    en: "Delete",
    fr: "Supprimer",
    de: "Löschen",
    ru: "Удалить",
    zh: "删除",
  },
  "common.edit": {
    es: "Editar",
    en: "Edit",
    fr: "Modifier",
    de: "Bearbeiten",
    ru: "Редактировать",
    zh: "编辑",
  },
  "common.view": {
    es: "Ver",
    en: "View",
    fr: "Voir",
    de: "Ansehen",
    ru: "Просмотр",
    zh: "查看",
  },
  "common.search": {
    es: "Buscar",
    en: "Search",
    fr: "Rechercher",
    de: "Suchen",
    ru: "Поиск",
    zh: "搜索",
  },
  "common.filter": {
    es: "Filtrar",
    en: "Filter",
    fr: "Filtrer",
    de: "Filtern",
    ru: "Фильтр",
    zh: "筛选",
  },
  "common.sort": {
    es: "Ordenar",
    en: "Sort",
    fr: "Trier",
    de: "Sortieren",
    ru: "Сортировка",
    zh: "排序",
  },
  "common.select": {
    es: "Seleccionar",
    en: "Select",
    fr: "Sélectionner",
    de: "Auswählen",
    ru: "Выбрать",
    zh: "选择",
  },
  "common.required": {
    es: "Requerido",
    en: "Required",
    fr: "Requis",
    de: "Erforderlich",
    ru: "Обязательно",
    zh: "必填",
  },
  "common.preparing": {
    es: "Preparando...",
    en: "Preparing...",
    fr: "Préparation...",
    de: "Vorbereitung...",
    ru: "Подготовка...",
    zh: "准备中...",
  },

  // Excursions Page
  "excursions.title": {
    es: "Excursiones en Tenerife",
    en: "Excursions in Tenerife",
    fr: "Excursions à Tenerife",
    de: "Ausflüge auf Teneriffa",
    ru: "Экскурсии на Тенерифе",
    zh: "特内里费游览",
  },
  "excursions.subtitle": {
    es: "Descubre todas nuestras aventuras y experiencias únicas",
    en: "Discover all our unique adventures and experiences",
    fr: "Découvrez toutes nos aventures et expériences uniques",
    de: "Entdecken Sie all unsere einzigartigen Abenteuer und Erlebnisse",
    ru: "Откройте для себя все наши уникальные приключения и впечатления",
    zh: "发现我们所有独特的冒险和体验",
  },
  "excursions.hero_title": {
    es: "Descubre Tenerife",
    en: "Discover Tenerife",
    fr: "Découvrez Tenerife",
    de: "Entdecke Teneriffa",
    ru: "Откройте Тенерифе",
    zh: "发现特内里费",
  },
  "excursions.hero_subtitle_highlight": {
    es: "Como Nunca Antes",
    en: "Like Never Before",
    fr: "Comme Jamais Auparavant",
    de: "Wie Nie Zuvor",
    ru: "Как Никогда Раньше",
    zh: "前所未有",
  },
  "excursions.hero_description": {
    es: "Vive experiencias únicas en la isla más espectacular de Canarias. Desde aventuras en la naturaleza hasta tours gastronómicos, tenemos la excursión perfecta para ti.",
    en: "Live unique experiences on the most spectacular island of the Canaries. From nature adventures to gastronomic tours, we have the perfect excursion for you.",
    fr: "Vivez des expériences uniques sur l'île la plus spectaculaire des Canaries. Des aventures dans la nature aux visites gastronomiques, nous avons l'excursion parfaite pour vous.",
    de: "Erleben Sie einzigartige Erfahrungen auf der spektakulärsten Insel der Kanaren. Von Naturabenteuern bis hin zu gastronomischen Touren haben wir den perfekten Ausflug für Sie.",
    ru: "Получите уникальные впечатления на самом захватывающем острове Канарских островов. От приключений на природе до гастрономических туров — у нас есть идеальная экскурсия для вас.",
    zh: "在加那利群岛最壮观的岛屿上体验独特的经历。从自然探险到美食之旅，我们为您准备了完美的游览。",
  },
  "excursions.stat_experiences": {
    es: "Experiencias Únicas",
    en: "Unique Experiences",
    fr: "Expériences Uniques",
    de: "Einzigartige Erlebnisse",
    ru: "Уникальные Впечатления",
    zh: "独特体验",
  },
  "excursions.stat_rating": {
    es: "Valoración Media",
    en: "Average Rating",
    fr: "Évaluation Moyenne",
    de: "Durchschnittliche Bewertung",
    ru: "Средний Рейтинг",
    zh: "平均评分",
  },
  "excursions.stat_satisfaction": {
    es: "Satisfacción Garantizada",
    en: "Satisfaction Guaranteed",
    fr: "Satisfaction Garantie",
    de: "Zufriedenheit Garantiert",
    ru: "Гарантия Удовлетворенности",
    zh: "满意保证",
  },
  "excursions.filters": {
    es: "Filtros",
    en: "Filters",
    fr: "Filtres",
    de: "Filter",
    ru: "Фильтры",
    zh: "筛选器",
  },
  "excursions.search_placeholder": {
    es: "Buscar excursiones...",
    en: "Search excursions...",
    fr: "Rechercher des excursions...",
    de: "Ausflüge suchen...",
    ru: "Поиск экскурсий...",
    zh: "搜索游览...",
  },
  "excursions.all_categories": {
    es: "Todas las categorías",
    en: "All categories",
    fr: "Toutes les catégories",
    de: "Alle Kategorien",
    ru: "Все категории",
    zh: "所有类别",
  },
  "excursions.all_prices": {
    es: "Todos los precios",
    en: "All prices",
    fr: "Tous les prix",
    de: "Alle Preise",
    ru: "Все цены",
    zh: "所有价格",
  },
  "excursions.price_low": {
    es: "Menos de €50",
    en: "Less than €50",
    fr: "Moins de 50 €",
    de: "Weniger als 50 €",
    ru: "Меньше €50",
    zh: "低于€50",
  },
  "excursions.price_medium": {
    es: "€50 - €80",
    en: "€50 - €80",
    fr: "50 € - 80 €",
    de: "50 € - 80 €",
    ru: "€50 - €80",
    zh: "€50 - €80",
  },
  "excursions.price_high": {
    es: "Más de €80",
    en: "More than €80",
    fr: "Plus de 80 €",
    de: "Mehr als 80 €",
    ru: "Больше €80",
    zh: "高于€80",
  },
  "excursions.sort_featured": {
    es: "Destacados",
    en: "Featured",
    fr: "Mis en avant",
    de: "Empfohlen",
    ru: "Рекомендуемые",
    zh: "特色推荐",
  },
  "excursions.sort_price_low": {
    es: "Precio: Bajo a Alto",
    en: "Price: Low to High",
    fr: "Prix : Bas à Élevé",
    de: "Preis: Niedrig bis Hoch",
    ru: "Цена: от низкой к высокой",
    zh: "价格：从低到高",
  },
  "excursions.sort_price_high": {
    es: "Precio: Alto a Bajo",
    en: "Price: High to Low",
    fr: "Prix : Élevé à Bas",
    de: "Preis: Hoch bis Niedrig",
    ru: "Цена: от высокой к низкой",
    zh: "价格：从高到低",
  },
  "excursions.sort_name": {
    es: "Nombre: A-Z",
    en: "Name: A-Z",
    fr: "Nom : A-Z",
    de: "Name: A-Z",
    ru: "Название: А-Я",
    zh: "名称：A-Z",
  },
  "excursions.clear_filters": {
    es: "Limpiar filtros",
    en: "Clear filters",
    fr: "Effacer les filtres",
    de: "Filter löschen",
    ru: "Очистить фильтры",
    zh: "清除筛选",
  },
  "excursions.found": {
    es: "excursión encontrada",
    en: "excursion found",
    fr: "excursion trouvée",
    de: "Ausflug gefunden",
    ru: "экскурсия найдена",
    zh: "找到游览",
  },
  "excursions.found_plural": {
    es: "excursiones encontradas",
    en: "excursions found",
    fr: "excursions trouvées",
    de: "Ausflüge gefunden",
    ru: "экскурсий найдено",
    zh: "找到游览",
  },
  "excursions.showing_all": {
    es: "Mostrando todas las experiencias",
    en: "Showing all experiences",
    fr: "Affichage de toutes les expériences",
    de: "Alle Erlebnisse anzeigen",
    ru: "Отображение всех впечатлений",
    zh: "显示所有体验",
  },
  "excursions.filtered_from": {
    es: "Filtrado de",
    en: "Filtered from",
    fr: "Filtré de",
    de: "Gefiltert von",
    ru: "Отфильтровано из",
    zh: "从筛选",
  },
  "excursions.total_experiences": {
    es: "experiencias totales",
    en: "total experiences",
    fr: "expériences totales",
    de: "Gesamterlebnisse",
    ru: "всего впечатлений",
    zh: "总体验",
  },
  "excursions.no_results": {
    es: "No se encontraron excursiones",
    en: "No excursions found",
    fr: "Aucune excursion trouvée",
    de: "Keine Ausflüge gefunden",
    ru: "Экскурсии не найдены",
    zh: "未找到游览",
  },
  "excursions.no_results_text": {
    es: "Prueba a cambiar los filtros o a buscar con otros términos.",
    en: "Try changing the filters or searching with other terms.",
    fr: "Essayez de modifier les filtres ou de rechercher avec d'autres termes.",
    de: "Versuchen Sie, die Filter zu ändern oder mit anderen Begriffen zu suchen.",
    ru: "Попробуйте изменить фильтры или поискать по другим терминам.",
    zh: "尝试更改筛选条件或使用其他术语搜索。",
  },
  "excursions.view_all": {
    es: "Ver todas las excursiones",
    en: "View all excursions",
    fr: "Voir toutes les excursions",
    de: "Alle Ausflüge ansehen",
    ru: "Посмотреть все экскурсии",
    zh: "查看所有游览",
  },
  "excursions.custom_experience": {
    es: "¿Buscas una experiencia a medida?",
    en: "Looking for a custom experience?",
    fr: "Vous cherchez une expérience sur mesure ?",
    de: "Suchen Sie ein maßgeschneidertes Erlebnis?",
    ru: "Ищете индивидуальный опыт?",
    zh: "寻找定制体验？",
  },
  "excursions.custom_text": {
    es: "Contáctanos y crearemos la aventura perfecta para ti y tu grupo.",
    en: "Contact us and we will create the perfect adventure for you and your group.",
    fr: "Contactez-nous et nous créerons l'aventure parfaite pour vous et votre groupe.",
    de: "Kontaktieren Sie uns und wir erstellen das perfekte Abenteuer für Sie und Ihre Gruppe.",
    ru: "Свяжитесь с нами, и мы создадим идеальное приключение для вас и вашей группы.",
    zh: "联系我们，我们将为您和您的团队打造完美的冒险之旅。",
  },
  "excursions.contact_custom": {
    es: "Contactar para personalizar",
    en: "Contact to customize",
    fr: "Contacter pour personnaliser",
    de: "Kontakt zur Anpassung",
    ru: "Связаться для настройки",
    zh: "联系以定制",
  },
  "excursion.bookNow": {
    es: "Reservar Ahora",
    en: "Book Now",
    fr: "Réserver Maintenant",
    de: "Jetzt Buchen",
    ru: "Забронировать",
    zh: "立即预订",
  },
  "excursion.viewDetails": {
    es: "Ver Detalles",
    en: "View Details",
    fr: "Voir les Détails",
    de: "Details Ansehen",
    ru: "Подробнее",
    zh: "查看详情",
  },
  "excursion.from": {
    es: "desde",
    en: "from",
    fr: "à partir de",
    de: "ab",
    ru: "от",
    zh: "从",
  },
  "excursion.perPerson": {
    es: "por persona",
    en: "per person",
    fr: "par personne",
    de: "pro Person",
    ru: "на человека",
    zh: "每人",
  },
  "excursion.hours": {
    es: "horas",
    en: "hours",
    fr: "heures",
    de: "Stunden",
    ru: "часов",
    zh: "小时",
  },
  "excursion.maxPeople": {
    // Added from previous QuickEdit
    es: "Máx. {count} personas",
    en: "Max. {count} people",
    fr: "Max. {count} personnes",
    de: "Max. {count} Personen",
    ru: "Макс. {count} человек",
    zh: "最多 {count} 人",
  },

  // Services (for ExcursionCard)
  "services.included": {
    es: "servicios incluidos",
    en: "services included",
    fr: "services inclus",
    de: "enthaltene Leistungen",
    ru: "услуг включено",
    zh: "包含服务",
  },
  "services.not_included": {
    es: "servicios no incluidos",
    en: "services not included",
    fr: "services non inclus",
    de: "nicht enthaltene Leistungen",
    ru: "услуг не включено",
    zh: "不包含服务",
  },

  // Contact Page
  "contact.title": {
    es: "Contacta con Nosotros",
    en: "Contact Us",
    fr: "Contactez-Nous",
    de: "Kontaktiere Uns",
    ru: "Свяжитесь с Нами",
    zh: "联系我们",
  },
  "contact.hero_badge": {
    es: "Estamos aquí para ayudarte",
    en: "We're here to help you",
    fr: "Nous sommes là pour vous aider",
    de: "Wir sind hier um dir zu helfen",
    ru: "Мы здесь, чтобы помочь вам",
    zh: "我们在这里帮助您",
  },
  "contact.hero_subtitle": {
    es: "Tu aventura en Tenerife comienza aquí",
    en: "Your Tenerife adventure starts here",
    fr: "Votre aventure à Tenerife commence ici",
    de: "Dein Teneriffa-Abenteuer beginnt hier",
    ru: "Ваше приключение на Тенерифе начинается здесь",
    zh: "您的特内里费冒险从这里开始",
  },
  "contact.subtitle": {
    es: "¿Tienes preguntas o necesitas ayuda para planificar tu viaje? Nuestro equipo está listo para asistirte.",
    en: "Have questions or need help planning your trip? Our team is ready to assist you.",
    fr: "Vous avez des questions ou besoin d'aide pour planifier votre voyage ? Notre équipe est prête à vous aider.",
    de: "Haben Sie Fragen oder benötigen Sie Hilfe bei der Planung Ihrer Reise? Unser Team steht Ihnen gerne zur Verfügung.",
    ru: "Есть вопросы или нужна помощь в планировании поездки? Наша команда готова вам помочь.",
    zh: "有任何问题或需要帮助规划您的旅行吗？我们的团队随时准备为您提供帮助。",
  },
  "contact.subtitle_extended": {
    es: "Ofrecemos múltiples canales de comunicación para tu comodidad.",
    en: "We offer multiple communication channels for your convenience.",
    fr: "Nous offrons plusieurs canaux de communication pour votre commodité.",
    de: "Wir bieten mehrere Kommunikationskanäle für Ihre Bequemlichkeit.",
    ru: "Мы предлагаем несколько каналов связи для вашего удобства.",
    zh: "我们提供多种沟通渠道以方便您。",
  },
  "contact_info.phone": {
    es: "Teléfono",
    en: "Phone",
    fr: "Téléphone",
    de: "Telefon",
    ru: "Телефон",
    zh: "电话",
  },
  "contact_info.available": {
    es: "Disponible 24/7",
    en: "Available 24/7",
    fr: "Disponible 24/7",
    de: "Verfügbar 24/7",
    ru: "Доступно 24/7",
    zh: "24/7 可用",
  },
  "contact_info.whatsapp": {
    es: "WhatsApp",
    en: "WhatsApp",
    fr: "WhatsApp",
    de: "WhatsApp",
    ru: "WhatsApp",
    zh: "WhatsApp",
  },
  "contact_info.immediate_response": {
    es: "Respuesta inmediata",
    en: "Immediate response",
    fr: "Réponse immédiate",
    de: "Sofortige Antwort",
    ru: "Немедленный ответ",
    zh: "即时回复",
  },
  "contact_info.email": {
    es: "Correo Electrónico",
    en: "Email",
    fr: "Email",
    de: "Email",
    ru: "Электронная почта",
    zh: "电子邮件",
  },
  "contact_info.response_time": {
    es: "Respuesta en menos de 24h",
    en: "Response in less than 24h",
    fr: "Réponse en moins de 24h",
    de: "Antwort in weniger als 24 Stunden",
    ru: "Ответ менее чем за 24 часа",
    zh: "24小时内回复",
  },
  "contact_info.location": {
    es: "Ubicación",
    en: "Location",
    fr: "Emplacement",
    de: "Standort",
    ru: "Местоположение",
    zh: "地点",
  },
  "contact_info.canary_islands": {
    es: "Islas Canarias, España",
    en: "Canary Islands, Spain",
    fr: "Îles Canaries, Espagne",
    de: "Kanarische Inseln, Spanien",
    ru: "Канарские острова, Испания",
    zh: "西班牙加那利群岛",
  },
  "contact.form_title": {
    es: "Envíanos un Mensaje",
    en: "Send us a Message",
    fr: "Envoyez-nous un Message",
    de: "Sende uns eine Nachricht",
    ru: "Отправьте нам Сообщение",
    zh: "给我们留言",
  },
  "contact.form_subtitle": {
    es: "Completa el formulario y te contactaremos a la brevedad.",
    en: "Complete the form and we will contact you shortly.",
    fr: "Remplissez le formulaire et nous vous contacterons sous peu.",
    de: "Füllen Sie das Formular aus und wir werden uns in Kürze bei Ihnen melden.",
    ru: "Заполните форму, и мы свяжемся с вами в ближайшее время.",
    zh: "填写表格，我们会尽快与您联系。",
  },
  "contact.name": {
    es: "Nombre",
    en: "Name",
    fr: "Nom",
    de: "Name",
    ru: "Имя",
    zh: "姓名",
  },
  "contact.email": {
    es: "Correo Electrónico",
    en: "Email",
    fr: "Email",
    de: "Email",
    ru: "Электронная почта",
    zh: "电子邮件",
  },
  "contact.phone": {
    es: "Teléfono (Opcional)",
    en: "Phone (Optional)",
    fr: "Téléphone (Optionnel)",
    de: "Telefon (Optional)",
    ru: "Телефон (необязательно)",
    zh: "电话（可选）",
  },
  "contact.message": {
    es: "Mensaje",
    en: "Message",
    fr: "Message",
    de: "Nachricht",
    ru: "Сообщение",
    zh: "留言",
  },
  "contact.send": {
    es: "Enviar Mensaje",
    en: "Send Message",
    fr: "Envoyer le Message",
    de: "Nachricht Senden",
    ru: "Отправить Сообщение",
    zh: "发送留言",
  },
  "contact.success_title": {
    es: "¡Mensaje Enviado!",
    en: "Message Sent!",
    fr: "Message Envoyé !",
    de: "Nachricht Gesendet!",
    ru: "Сообщение Отправлено!",
    zh: "留言已发送！",
  },
  "contact.success_message": {
    es: "Gracias por contactarnos. Te responderemos lo antes posible.",
    en: "Thank you for contacting us. We will get back to you as soon as possible.",
    fr: "Merci de nous avoir contactés. Nous vous répondrons dès que possible.",
    de: "Vielen Dank für Ihre Kontaktaufnahme. Wir werden uns so schnell wie möglich bei Ihnen melden.",
    ru: "Спасибо за обращение. Мы свяжемся с вами как можно скорее.",
    zh: "感谢您联系我们。我们会尽快回复您。",
  },
  "contact.send_another": {
    es: "Enviar Otro Mensaje",
    en: "Send Another Message",
    fr: "Envoyer un Autre Message",
    de: "Weitere Nachricht Senden",
    ru: "Отправить Еще Одно Сообщение",
    zh: "发送另一条留言",
  },
  "contact.whatsapp_contact": {
    es: "Contactar por WhatsApp",
    en: "Contact via WhatsApp",
    fr: "Contacter par WhatsApp",
    de: "Kontakt per WhatsApp",
    ru: "Связаться через WhatsApp",
    zh: "通过WhatsApp联系",
  },
  "contact.immediate_contact": {
    es: "Contacto Inmediato",
    en: "Immediate Contact",
    fr: "Contact Immédiat",
    de: "Sofortiger Kontakt",
    ru: "Немедленный Контакт",
    zh: "即时联系",
  },
  "contact.quick_response_question": {
    es: "¿Necesitas una respuesta rápida? ¡Escríbenos por WhatsApp!",
    en: "Need a quick answer? Write to us on WhatsApp!",
    fr: "Besoin d'une réponse rapide ? Écrivez-nous sur WhatsApp !",
    de: "Benötigen Sie eine schnelle Antwort? Schreiben Sie uns auf WhatsApp!",
    ru: "Нужен быстрый ответ? Напишите нам в WhatsApp!",
    zh: "需要快速回复吗？请通过WhatsApp联系我们！",
  },
  "contact.open_whatsapp": {
    es: "Abrir Chat en WhatsApp",
    en: "Open Chat on WhatsApp",
    fr: "Ouvrir le Chat sur WhatsApp",
    de: "Chat auf WhatsApp Öffnen",
    ru: "Открыть Чат в WhatsApp",
    zh: "在WhatsApp上打开聊天",
  },
  "contact.attention_schedule": {
    es: "Horario de Atención",
    en: "Attention Schedule",
    fr: "Horaires d'Attention",
    de: "Öffnungszeiten",
    ru: "График Работы",
    zh: "服务时间",
  },
  "contact.schedule_text": {
    es: "Lunes a Domingo: 8:00 - 20:00 (Hora Canaria)",
    en: "Monday to Sunday: 8:00 AM - 8:00 PM (Canary Time)",
    fr: "Lundi à Dimanche : 8h00 - 20h00 (Heure des Canaries)",
    de: "Montag bis Sonntag: 8:00 - 20:00 Uhr (Kanarische Zeit)",
    ru: "Понедельник - Воскресенье: 8:00 - 20:00 (Канарское время)",
    zh: "周一至周日：上午8:00 - 晚上8:00（加那利时间）",
  },
  "contact.why_choose_us": {
    es: "¿Por Qué Elegirnos?",
    en: "Why Choose Us?",
    fr: "Pourquoi Nous Choisir ?",
    de: "Warum Uns Wählen?",
    ru: "Почему Выбирают Нас?",
    zh: "为什么选择我们？",
  },
  "trust.guaranteed_response": {
    es: "Respuesta Garantizada",
    en: "Guaranteed Response",
    fr: "Réponse Garantie",
    de: "Garantierte Antwort",
    ru: "Гарантированный Ответ",
    zh: "保证回复",
  },
  "trust.guaranteed_text": {
    es: "Nos comprometemos a responder todas tus consultas rápidamente.",
    en: "We are committed to answering all your inquiries quickly.",
    fr: "Nous nous engageons à répondre rapidement à toutes vos demandes.",
    de: "Wir verpflichten uns, alle Ihre Anfragen schnell zu beantworten.",
    ru: "Мы обязуемся быстро отвечать на все ваши запросы.",
    zh: "我们承诺快速回复您的所有咨询。",
  },
  "trust.personal_attention": {
    es: "Atención Personalizada",
    en: "Personalized Attention",
    fr: "Attention Personnalisée",
    de: "Persönliche Betreuung",
    ru: "Персональное Внимание",
    zh: "个性化关注",
  },
  "trust.personal_text": {
    es: "Trato cercano y adaptado a tus necesidades de viaje.",
    en: "Close treatment adapted to your travel needs.",
    fr: "Un traitement proche adapté à vos besoins de voyage.",
    de: "Nahe Betreuung, angepasst an Ihre Reisebedürfnisse.",
    ru: "Тесное общение, адаптированное к вашим потребностям в путешествии.",
    zh: "贴心服务，满足您的旅行需求。",
  },
  "trust.multilingual": {
    es: "Soporte Multilingüe",
    en: "Multilingual Support",
    fr: "Support Multilingue",
    de: "Mehrsprachige Unterstützung",
    ru: "Многоязычная Поддержка",
    zh: "多语言支持",
  },
  "trust.multilingual_text": {
    es: "Te atendemos en tu idioma para una mejor comunicación.",
    en: "We assist you in your language for better communication.",
    fr: "Nous vous assistons dans votre langue pour une meilleure communication.",
    de: "Wir betreuen Sie in Ihrer Sprache für eine bessere Kommunikation.",
    ru: "Мы обслуживаем вас на вашем языке для лучшего общения.",
    zh: "我们用您的语言为您提供服务，以便更好地沟通。",
  },
  "trust.service_passion": {
    es: "Pasión por el Servicio",
    en: "Passion for Service",
    fr: "Passion pour le Service",
    de: "Leidenschaft für Service",
    ru: "Страсть к Обслуживанию",
    zh: "服务热情",
  },
  "trust.service_text": {
    es: "Amamos lo que hacemos y queremos compartirlo contigo.",
    en: "We love what we do and we want to share it with you.",
    fr: "Nous aimons ce que nous faisons et nous voulons le partager avec vous.",
    de: "Wir lieben, was wir tun, und möchten es mit Ihnen teilen.",
    ru: "Мы любим то, что делаем, и хотим поделиться этим с вами.",
    zh: "我们热爱我们的工作，并希望与您分享。",
  },
  "contact.faq": {
    es: "Preguntas Frecuentes",
    en: "FAQ",
    fr: "FAQ",
    de: "FAQ",
    ru: "ЧаВо",
    zh: "常见问题",
  },
  "contact.how_to_book": {
    es: "¿Cómo puedo reservar una excursión?",
    en: "How can I book an excursion?",
    fr: "Comment puis-je réserver une excursion ?",
    de: "Wie kann ich einen Ausflug buchen?",
    ru: "Как я могу забронировать экскурсию?",
    zh: "我如何预订游览？",
  },
  "contact.how_to_book_answer": {
    es: "Puedes reservar directamente en nuestra web, por WhatsApp o email.",
    en: "You can book directly on our website, via WhatsApp, or email.",
    fr: "Vous pouvez réserver directement sur notre site web, via WhatsApp ou par email.",
    de: "Sie können direkt auf unserer Website, per WhatsApp oder E-Mail buchen.",
    ru: "Вы можете забронировать прямо на нашем сайте, через WhatsApp или по электронной почте.",
    zh: "您可以直接在我们的网站上、通过WhatsApp或电子邮件预订。",
  },
  "contact.what_includes": {
    es: "¿Qué incluyen las excursiones?",
    en: "What do the excursions include?",
    fr: "Qu'incluent les excursions ?",
    de: "Was beinhalten die Ausflüge?",
    ru: "Что включено в экскурсии?",
    zh: "游览包含哪些内容？",
  },
  "contact.what_includes_answer": {
    es: "Cada excursión tiene detalles específicos, revisa la descripción o consúltanos.",
    en: "Each excursion has specific details, check the description or ask us.",
    fr: "Chaque excursion a des détails spécifiques, consultez la description ou demandez-nous.",
    de: "Jeder Ausflug hat spezifische Details, überprüfen Sie die Beschreibung oder fragen Sie uns.",
    ru: "Каждая экскурсия имеет свои особенности, проверьте описание или спросите нас.",
    zh: "每次游览都有具体细节，请查看描述或咨询我们。",
  },
  "contact.group_discounts": {
    es: "¿Ofrecen descuentos para grupos?",
    en: "Do you offer group discounts?",
    fr: "Offrez-vous des réductions pour les groupes ?",
    de: "Bieten Sie Gruppenrabatte an?",
    ru: "Предлагаете ли вы скидки для групп?",
    zh: "你们提供团体折扣吗？",
  },
  "contact.group_discounts_answer": {
    es: "Sí, contáctanos para más información sobre descuentos para grupos.",
    en: "Yes, contact us for more information on group discounts.",
    fr: "Oui, contactez-nous pour plus d'informations sur les réductions pour groupes.",
    de: "Ja, kontaktieren Sie uns für weitere Informationen zu Gruppenrabatten.",
    ru: "Да, свяжитесь с нами для получения дополнительной информации о групповых скидках.",
    zh: "是的，请联系我们了解更多关于团体折扣的信息。",
  },

  // About Page
  "about.title": {
    es: "Sobre Nosotros",
    en: "About Us",
    fr: "À Propos de Nous",
    de: "Über Uns",
    ru: "О Нас",
    zh: "关于我们",
  },
  "about.hero_badge": {
    es: "Nuestra Historia",
    en: "Our Story",
    fr: "Notre Histoire",
    de: "Unsere Geschichte",
    ru: "Наша История",
    zh: "我们的故事",
  },
  "about.subtitle": {
    es: "Apasionados por Tenerife, Dedicados a Ti",
    en: "Passionate about Tenerife, Dedicated to You",
    fr: "Passionnés par Tenerife, Dédiés à Vous",
    de: "Leidenschaftlich für Teneriffa, Ihnen Gewidmet",
    ru: "Увлечены Тенерифе, Преданы Вам",
    zh: "热爱特内里费，竭诚为您服务",
  },
  "about.description": {
    es: "Somos un equipo local con un profundo amor por Tenerife y un deseo de compartir su belleza y cultura contigo. Creamos experiencias auténticas y memorables.",
    en: "We are a local team with a deep love for Tenerife and a desire to share its beauty and culture with you. We create authentic and memorable experiences.",
    fr: "Nous sommes une équipe locale avec un amour profond pour Tenerife et un désir de partager sa beauté et sa culture avec vous. Nous créons des expériences authentiques et mémorables.",
    de: "Wir sind ein lokales Team mit einer tiefen Liebe zu Teneriffa und dem Wunsch, seine Schönheit und Kultur mit Ihnen zu teilen. Wir schaffen authentische und unvergessliche Erlebnisse.",
    ru: "Мы — местная команда с глубокой любовью к Тенерифе и желанием поделиться с вами его красотой и культурой. Мы создаем аутентичные и запоминающиеся впечатления.",
    zh: "我们是一支热爱特内里费的本地团队，渴望与您分享其美丽和文化。我们创造真实而难忘的体验。",
  },
  "about.achievements": {
    es: "Nuestros Logros",
    en: "Our Achievements",
    fr: "Nos Réalisations",
    de: "Unsere Erfolge",
    ru: "Наши Достижения",
    zh: "我们的成就",
  },
  "about.achievements_subtitle": {
    es: "Comprometidos con la excelencia y la satisfacción del cliente.",
    en: "Committed to excellence and customer satisfaction.",
    fr: "Engagés envers l'excellence et la satisfaction client.",
    de: "Verpflichtet zu Exzellenz und Kundenzufriedenheit.",
    ru: "Привержены совершенству и удовлетворенности клиентов.",
    zh: "致力于卓越和客户满意度。",
  },
  "about.stat_excursions": {
    es: "Excursiones Ofrecidas",
    en: "Excursions Offered",
    fr: "Excursions Proposées",
    de: "Angebotene Ausflüge",
    ru: "Предлагаемые Экскурсии",
    zh: "提供的游览",
  },
  "about.stat_rating": {
    es: "Valoración de Clientes",
    en: "Customer Rating",
    fr: "Évaluation des Clients",
    de: "Kundenbewertung",
    ru: "Рейтинг Клиентов",
    zh: "客户评分",
  },
  "about.story_badge": {
    es: "Nuestra Esencia",
    en: "Our Essence",
    fr: "Notre Essence",
    de: "Unsere Essenz",
    ru: "Наша Суть",
    zh: "我们的精髓",
  },
  "about.story_title": {
    es: "Nacidos de la Pasión por Tenerife",
    en: "Born from a Passion for Tenerife",
    fr: "Nés d'une Passion pour Tenerife",
    de: "Geboren aus Leidenschaft für Teneriffa",
    ru: "Рожденные из Страсти к Тенерифе",
    zh: "源于对特内里费的热爱",
  },
  "about.team_subtitle": {
    es: "Conectando con la cultura local",
    en: "Connecting with local culture",
    fr: "Connexion avec la culture locale",
    de: "Verbindung mit der lokalen Kultur",
    ru: "Связь с местной культурой",
    zh: "与当地文化联系",
  },
  "about.pillars_title": {
    es: "Nuestros Pilares Fundamentales",
    en: "Our Fundamental Pillars",
    fr: "Nos Piliers Fondamentaux",
    de: "Unsere Grundpfeiler",
    ru: "Наши Основополагающие Принципы",
    zh: "我们的基本支柱",
  },
  "about.pillars_subtitle": {
    es: "Misión, Visión y Valores que nos guían.",
    en: "Mission, Vision, and Values that guide us.",
    fr: "Mission, Vision et Valeurs qui nous guident.",
    de: "Mission, Vision und Werte, die uns leiten.",
    ru: "Миссия, Видение и Ценности, которые нами руководят.",
    zh: "指导我们的使命、愿景和价值观。",
  },
  "about.mission": {
    es: "Nuestra Misión",
    en: "Our Mission",
    fr: "Notre Mission",
    de: "Unsere Mission",
    ru: "Наша Миссия",
    zh: "我们的使命",
  },
  "about.mission_text": {
    es: "Ofrecer experiencias auténticas y memorables, mostrando la verdadera esencia de Tenerife con pasión y profesionalismo.",
    en: "To offer authentic and memorable experiences, showcasing the true essence of Tenerife with passion and professionalism.",
    fr: "Offrir des expériences authentiques et mémorables, mettant en valeur la véritable essence de Tenerife avec passion et professionnalisme.",
    de: "Authentische und unvergessliche Erlebnisse zu bieten, die wahre Essenz Teneriffas mit Leidenschaft und Professionalität zu zeigen.",
    ru: "Предлагать аутентичные и запоминающиеся впечатления, демонстрируя истинную суть Тенерифе со страстью и профессионализмом.",
    zh: "提供真实而难忘的体验，以热情和专业精神展示特内里费的真正精髓。",
  },
  "about.vision": {
    es: "Nuestra Visión",
    en: "Our Vision",
    fr: "Notre Vision",
    de: "Unsere Vision",
    ru: "Наше Видение",
    zh: "我们的愿景",
  },
  "about.vision_text": {
    es: "Ser la empresa líder en excursiones en Tenerife, reconocida por nuestra calidad, innovación y compromiso con el turismo sostenible.",
    en: "To be the leading excursion company in Tenerife, recognized for our quality, innovation, and commitment to sustainable tourism.",
    fr: "Être l'entreprise leader des excursions à Tenerife, reconnue pour notre qualité, notre innovation et notre engagement envers le tourisme durable.",
    de: "Das führende Ausflugsunternehmen auf Teneriffa zu sein, anerkannt für unsere Qualität, Innovation und unser Engagement für nachhaltigen Tourismus.",
    ru: "Быть ведущей экскурсионной компанией на Тенерифе, признанной за наше качество, инновации и приверженность устойчивому туризму.",
    zh: "成为特内里费领先的游览公司，以我们的质量、创新和对可持续旅游的承诺而闻名。",
  },
  "about.values": {
    es: "Nuestros Valores",
    en: "Our Values",
    fr: "Nos Valeurs",
    de: "Unsere Werte",
    ru: "Наши Ценности",
    zh: "我们的价值观",
  },
  "about.values_text": {
    es: "Pasión, Calidad, Seguridad, Sostenibilidad, Autenticidad y Respeto.",
    en: "Passion, Quality, Safety, Sustainability, Authenticity, and Respect.",
    fr: "Passion, Qualité, Sécurité, Durabilité, Authenticité et Respect.",
    de: "Leidenschaft, Qualität, Sicherheit, Nachhaltigkeit, Authentizität und Respekt.",
    ru: "Страсть, Качество, Безопасность, Устойчивость, Аутентичность и Уважение.",
    zh: "热情、质量、安全、可持续性、真实性和尊重。",
  },
  "about.value_passion_title": {
    es: "Pasión por Tenerife",
    en: "Passion for Tenerife",
    fr: "Passion pour Tenerife",
    de: "Leidenschaft für Teneriffa",
    ru: "Страсть к Тенерифе",
    zh: "对特内里费的热情",
  },
  "about.value_passion_desc": {
    es: "Amamos nuestra isla y transmitimos esa pasión en cada experiencia.",
    en: "We love our island and convey that passion in every experience.",
    fr: "Nous aimons notre île et transmettons cette passion dans chaque expérience.",
    de: "Wir lieben unsere Insel und vermitteln diese Leidenschaft in jedem Erlebnis.",
    ru: "Мы любим наш остров и передаем эту страсть в каждом впечатлении.",
    zh: "我们热爱我们的岛屿，并在每一次体验中传递这种热情。",
  },
  "about.value_experience_title": {
    es: "Experiencia Local",
    en: "Local Experience",
    fr: "Expérience Locale",
    de: "Lokale Erfahrung",
    ru: "Местный Опыт",
    zh: "本地体验",
  },
  "about.value_experience_desc": {
    es: "Conocimiento profundo para ofrecerte lo mejor de Tenerife.",
    en: "Deep knowledge to offer you the best of Tenerife.",
    fr: "Une connaissance approfondie pour vous offrir le meilleur de Tenerife.",
    de: "Tiefes Wissen, um Ihnen das Beste von Teneriffa zu bieten.",
    ru: "Глубокие знания, чтобы предложить вам лучшее на Тенерифе.",
    zh: "深厚的知识，为您提供特内里费最好的体验。",
  },
  "about.value_security_title": {
    es: "Seguridad Primero",
    en: "Safety First",
    fr: "Sécurité d'Abord",
    de: "Sicherheit Zuerst",
    ru: "Безопасность Прежде Всего",
    zh: "安全第一",
  },
  "about.value_security_desc": {
    es: "Tu bienestar es nuestra máxima prioridad en todas las actividades.",
    en: "Your well-being is our top priority in all activities.",
    fr: "Votre bien-être est notre priorité absolue dans toutes les activités.",
    de: "Ihr Wohlbefinden hat bei allen Aktivitäten oberste Priorität.",
    ru: "Ваше благополучие — наш главный приоритет во всех мероприятиях.",
    zh: "您的福祉是我们所有活动中的重中之重。",
  },
  "about.value_quality_title": {
    es: "Calidad Superior",
    en: "Superior Quality",
    fr: "Qualité Supérieure",
    de: "Überlegene Qualität",
    ru: "Высшее Качество",
    zh: "卓越品质",
  },
  "about.value_quality_desc": {
    es: "Nos esforzamos por la excelencia en cada detalle de tu aventura.",
    en: "We strive for excellence in every detail of your adventure.",
    fr: "Nous visons l'excellence dans chaque détail de votre aventure.",
    de: "Wir streben nach Exzellenz in jedem Detail Ihres Abenteuers.",
    ru: "Мы стремимся к совершенству в каждой детали вашего приключения.",
    zh: "我们在您冒险的每一个细节中都力求卓越。",
  },
  "about.certifications_title": {
    es: "Nuestras Certificaciones",
    en: "Our Certifications",
    fr: "Nos Certifications",
    de: "Unsere Zertifizierungen",
    ru: "Наши Сертификаты",
    zh: "我们的认证",
  },
  "about.certifications_subtitle": {
    es: "Compromiso con la calidad y el turismo responsable.",
    en: "Commitment to quality and responsible tourism.",
    fr: "Engagement envers la qualité et le tourisme responsable.",
    de: "Engagement für Qualität und verantwortungsvollen Tourismus.",
    ru: "Приверженность качеству и ответственному туризму.",
    zh: "致力于质量和负责任的旅游。",
  },
  "about.cert_sustainable_tourism": {
    es: "Turismo Sostenible Certificado",
    en: "Certified Sustainable Tourism",
    fr: "Tourisme Durable Certifié",
    de: "Zertifizierter Nachhaltiger Tourismus",
    ru: "Сертифицированный Устойчивый Туризм",
    zh: "认证可持续旅游",
  },
  "about.cert_official_guides": {
    es: "Guías Oficiales de Canarias",
    en: "Official Canary Islands Guides",
    fr: "Guides Officiels des Canaries",
    de: "Offizielle Reiseführer der Kanarischen Inseln",
    ru: "Официальные Гиды Канарских Островов",
    zh: "加那利群岛官方导游",
  },
  "about.cert_responsible_company": {
    es: "Empresa Responsable",
    en: "Responsible Company",
    fr: "Entreprise Responsable",
    de: "Verantwortungsbewusstes Unternehmen",
    ru: "Ответственная Компания",
    zh: "负责任的公司",
  },
  "about.cert_tripadvisor_excellence": {
    es: "Excelencia TripAdvisor",
    en: "TripAdvisor Excellence",
    fr: "Excellence TripAdvisor",
    de: "TripAdvisor Exzellenz",
    ru: "Превосходство TripAdvisor",
    zh: "TripAdvisor卓越奖",
  },
  "about.cta_title": {
    es: "Únete a la Aventura",
    en: "Join the Adventure",
    fr: "Rejoignez l'Aventure",
    de: "Mach Mit Beim Abenteuer",
    ru: "Присоединяйтесь к Приключению",
    zh: "加入冒险",
  },
  "about.cta_description": {
    es: "Explora Tenerife con nosotros y crea recuerdos que durarán toda la vida. ¡Tu próxima gran experiencia te espera!",
    en: "Explore Tenerife with us and create memories that will last a lifetime. Your next great experience awaits!",
    fr: "Explorez Tenerife avec nous et créez des souvenirs qui dureront toute une vie. Votre prochaine grande expérience vous attend !",
    de: "Erkunden Sie Teneriffa mit uns und schaffen Sie Erinnerungen, die ein Leben lang halten. Ihr nächstes großes Erlebnis erwartet Sie!",
    ru: "Исследуйте Тенерифе вместе с нами и создайте воспоминания, которые останутся на всю жизнь. Ваше следующее большое приключение ждет вас!",
    zh: "与我们一起探索特内里费，创造终生难忘的回忆。您的下一次精彩体验正等待着您！",
  },
  "about.cta_view_excursions": {
    es: "Ver Excursiones",
    en: "View Excursions",
    fr: "Voir les Excursions",
    de: "Ausflüge Ansehen",
    ru: "Посмотреть Экскурсии",
    zh: "查看游览",
  },
  "about.cta_contact": {
    es: "Contactar",
    en: "Contact",
    fr: "Contacter",
    de: "Kontakt",
    ru: "Контакт",
    zh: "联系",
  },

  // Booking Pages
  "booking.title": {
    es: "Reserva tu Aventura en Tenerife",
    en: "Book Your Tenerife Adventure",
    fr: "Réservez Votre Aventure à Tenerife",
    de: "Buche Dein Teneriffa-Abenteuer",
    ru: "Забронируйте Ваше Приключение на Тенерифе",
    zh: "预订您的特内里费冒险之旅",
  },
  "booking.subtitle": {
    es: "Asegura tu plaza para las mejores experiencias en la isla.",
    en: "Secure your spot for the best experiences on the island.",
    fr: "Réservez votre place pour les meilleures expériences sur l'île.",
    de: "Sichere Dir Deinen Platz für die besten Erlebnisse auf der Insel.",
    ru: "Забронируйте свое место для лучших впечатлений на острове.",
    zh: "确保您在岛上获得最佳体验的位置。",
  },
  "booking.subtitle2": {
    es: "Confirmación instantánea y cancelación flexible.",
    en: "Instant confirmation and flexible cancellation.",
    fr: "Confirmation instantanée et annulation flexible.",
    de: "Sofortige Bestätigung und flexible Stornierung.",
    ru: "Мгновенное подтверждение и гибкая отмена.",
    zh: "即时确认和灵活取消。",
  },
  "booking.trust_confirmation": {
    es: "Confirmación Inmediata",
    en: "Immediate Confirmation",
    fr: "Confirmation Immédiate",
    de: "Sofortige Bestätigung",
    ru: "Мгновенное Подтверждение",
    zh: "即时确认",
  },
  "booking.trust_cancellation": {
    es: "Cancelación Flexible",
    en: "Flexible Cancellation",
    fr: "Annulation Flexible",
    de: "Flexible Stornierung",
    ru: "Гибкая Отмена",
    zh: "灵活取消",
  },
  "booking.trust_support": {
    es: "Soporte 24/7",
    en: "24/7 Support",
    fr: "Support 24/7",
    de: "24/7 Support",
    ru: "Поддержка 24/7",
    zh: "24/7 支持",
  },
  "booking.personal_info": {
    es: "Información Personal",
    en: "Personal Information",
    fr: "Informations Personnelles",
    de: "Persönliche Informationen",
    ru: "Личная Информация",
    zh: "个人信息",
  },
  "booking.excursion_details": {
    es: "Detalles de la Excursión",
    en: "Excursion Details",
    fr: "Détails de l'Excursion",
    de: "Details zum Ausflug",
    ru: "Детали Экскурсии",
    zh: "游览详情",
  },
  "booking.summary": {
    es: "Resumen de tu Reserva",
    en: "Your Booking Summary",
    fr: "Résumé de Votre Réservation",
    de: "Deine Buchungsübersicht",
    ru: "Сводка Вашего Бронирования",
    zh: "您的预订摘要",
  },
  "booking.select_excursion_message": {
    es: "Selecciona una excursión para ver el resumen.",
    en: "Select an excursion to see the summary.",
    fr: "Sélectionnez une excursion pour voir le résumé.",
    de: "Wähle einen Ausflug, um die Zusammenfassung zu sehen.",
    ru: "Выберите экскурсию, чтобы увидеть сводку.",
    zh: "选择一个游览项目以查看摘要。",
  },
  "booking.select_excursion_subtitle": {
    es: "Los detalles aparecerán aquí una vez elijas.",
    en: "Details will appear here once you choose.",
    fr: "Les détails apparaîtront ici une fois que vous aurez choisi.",
    de: "Details werden hier angezeigt, sobald Du wählst.",
    ru: "Детали появятся здесь после выбора.",
    zh: "选择后，详情将在此处显示。",
  },
  "booking.why_choose_us": {
    es: "¿Por Qué Elegirnos?",
    en: "Why Choose Us?",
    fr: "Pourquoi Nous Choisir ?",
    de: "Warum Uns Wählen?",
    ru: "Почему Выбирают Нас?",
    zh: "为什么选择我们？",
  },
  "booking.trust_guides": {
    es: "Guías Expertos Locales",
    en: "Expert Local Guides",
    fr: "Guides Locaux Experts",
    de: "Erfahrene Lokale Reiseführer",
    ru: "Опытные Местные Гиды",
    zh: "专业本地导游",
  },
  "booking.trust_groups": {
    es: "Grupos Pequeños y Amigables",
    en: "Small and Friendly Groups",
    fr: "Petits Groupes Conviviaux",
    de: "Kleine und Freundliche Gruppen",
    ru: "Маленькие и Дружелюбные Группы",
    zh: "小型友好团体",
  },
  "booking.people_count": {
    es: "{count} persona(s)",
    en: "{count} person(s)",
    fr: "{count} personne(s)",
    de: "{count} Person(en)",
    ru: "{count} человек(а)",
    zh: "{count} 人",
  },
  "booking.requests": {
    es: "Solicitudes Especiales",
    en: "Special Requests",
    fr: "Demandes Spéciales",
    de: "Sonderwünsche",
    ru: "Особые Пожелания",
    zh: "特殊要求",
  },
  "booking.requests_placeholder": {
    es: "Ej: Alergias, preferencias de asiento, etc.",
    en: "E.g., Allergies, seat preferences, etc.",
    fr: "Ex : Allergies, préférences de siège, etc.",
    de: "Z.B. Allergien, Sitzplatzpräferenzen, etc.",
    ru: "Пример: Аллергии, предпочтения по местам и т.д.",
    zh: "例如：过敏、座位偏好等。",
  },
  "booking.submit": {
    es: "Confirmar y Enviar Solicitud",
    en: "Confirm and Send Request",
    fr: "Confirmer et Envoyer la Demande",
    de: "Bestätigen und Anfrage Senden",
    ru: "Подтвердить и Отправить Запрос",
    zh: "确认并发送请求",
  },
  "booking.processing": {
    es: "Procesando...",
    en: "Processing...",
    fr: "Traitement...",
    de: "Verarbeite...",
    ru: "Обработка...",
    zh: "处理中...",
  },
  "booking.feature_confirmation": {
    es: "Confirmación Instantánea",
    en: "Instant Confirmation",
    fr: "Confirmation Instantanée",
    de: "Sofortige Bestätigung",
    ru: "Мгновенное Подтверждение",
    zh: "即时确认",
  },
  "booking.feature_confirmation_desc": {
    es: "Recibe tu confirmación de reserva al momento.",
    en: "Receive your booking confirmation instantly.",
    fr: "Recevez votre confirmation de réservation instantanément.",
    de: "Erhalte deine Buchungsbestätigung sofort.",
    ru: "Получите подтверждение бронирования мгновенно.",
    zh: "立即收到您的预订确认。",
  },
  "booking.feature_payment": {
    es: "Pago Seguro y Fácil",
    en: "Secure and Easy Payment",
    fr: "Paiement Sécurisé et Facile",
    de: "Sichere und Einfache Zahlung",
    ru: "Безопасная и Простая Оплата",
    zh: "安全便捷的支付",
  },
  "booking.feature_payment_desc": {
    es: "Múltiples opciones de pago seguras para tu comodidad.",
    en: "Multiple secure payment options for your convenience.",
    fr: "Plusieurs options de paiement sécurisées pour votre commodité.",
    de: "Mehrere sichere Zahlungsoptionen für deine Bequemlichkeit.",
    ru: "Несколько безопасных вариантов оплаты для вашего удобства.",
    zh: "多种安全支付方式供您选择。",
  },
  "booking.feature_experience": {
    es: "Experiencias Inolvidables",
    en: "Unforgettable Experiences",
    fr: "Expériences Inoubliables",
    de: "Unvergessliche Erlebnisse",
    ru: "Незабываемые Впечатления",
    zh: "难忘的经历",
  },
  "booking.feature_experience_desc": {
    es: "Creamos recuerdos que durarán toda la vida.",
    en: "We create memories that will last a lifetime.",
    fr: "Nous créons des souvenirs qui dureront toute une vie.",
    de: "Wir schaffen Erinnerungen, die ein Leben lang halten.",
    ru: "Мы создаем воспоминания, которые останутся на всю жизнь.",
    zh: "我们创造终生难忘的回忆。",
  },
  "booking.duration_label": {
    es: "Duración",
    en: "Duration",
    fr: "Durée",
    de: "Dauer",
    ru: "Продолжительность",
    zh: "持续时间",
  },
  "booking.category_label": {
    es: "Categoría",
    en: "Category",
    fr: "Catégorie",
    de: "Kategorie",
    ru: "Категория",
    zh: "类别",
  },
  "booking.rating_label": {
    es: "Valoración",
    en: "Rating",
    fr: "Évaluation",
    de: "Bewertung",
    ru: "Рейтинг",
    zh: "评分",
  },
  "booking.reviews_label": {
    es: "opiniones",
    en: "reviews",
    fr: "avis",
    de: "Bewertungen",
    ru: "отзывов",
    zh: "评论",
  },
  "booking.price_per_person": {
    es: "Precio por persona",
    en: "Price per person",
    fr: "Prix par personne",
    de: "Preis pro Person",
    ru: "Цена за человека",
    zh: "每人价格",
  },
  "booking.people_summary": {
    es: "Personas",
    en: "People",
    fr: "Personnes",
    de: "Personen",
    ru: "Человек",
    zh: "人数",
  },
  "booking.total_estimated": {
    es: "Total Estimado",
    en: "Estimated Total",
    fr: "Total Estimé",
    de: "Geschätzte Gesamtsumme",
    ru: "Ориентировочная Сумма",
    zh: "预计总额",
  },
  "booking.included_price": {
    es: "Incluido en el precio",
    en: "Included in the price",
    fr: "Inclus dans le prix",
    de: "Im Preis inbegriffen",
    ru: "Включено в стоимость",
    zh: "包含在价格中",
  },
  "booking.transport": {
    es: "Transporte",
    en: "Transport",
    fr: "Transport",
    de: "Transport",
    ru: "Транспорт",
    zh: "交通",
  },
  "booking.guide": {
    es: "Guía profesional",
    en: "Professional guide",
    fr: "Guide professionnel",
    de: "Professioneller Reiseführer",
    ru: "Профессиональный гид",
    zh: "专业导游",
  },
  "booking.insurance": {
    es: "Seguro de viaje",
    en: "Travel insurance",
    fr: "Assurance voyage",
    de: "Reiseversicherung",
    ru: "Страховка путешественника",
    zh: "旅游保险",
  },
  "booking.photos": {
    es: "Fotos de recuerdo",
    en: "Souvenir photos",
    fr: "Photos souvenirs",
    de: "Erinnerungsfotos",
    ru: "Сувенирные фотографии",
    zh: "纪念照片",
  },
  "booking.premium_label": {
    es: "Destacado",
    en: "Premium",
    fr: "Premium",
    de: "Premium",
    ru: "Премиум",
    zh: "高级",
  },
  "booking.whatsapp_greeting": {
    es: "¡Hola! Me gustaría reservar la siguiente excursión:",
    en: "Hello! I would like to book the following excursion:",
    fr: "Bonjour ! J'aimerais réserver l'excursion suivante :",
    de: "Hallo! Ich möchte folgenden Ausflug buchen:",
    ru: "Здравствуйте! Я хотел бы забронировать следующую экскурсию:",
    zh: "你好！我想预订以下游览：",
  },
  "booking.whatsapp_excursion": {
    es: "Excursión",
    en: "Excursion",
    fr: "Excursion",
    de: "Ausflug",
    ru: "Экскурсия",
    zh: "游览",
  },
  "booking.whatsapp_date": {
    es: "Fecha Preferida",
    en: "Preferred Date",
    fr: "Date Préférée",
    de: "Bevorzugtes Datum",
    ru: "Предпочтительная Дата",
    zh: "首选日期",
  },
  "booking.whatsapp_people": {
    es: "Nº Personas",
    en: "No. of People",
    fr: "Nº Personnes",
    de: "Anzahl Personen",
    ru: "Кол-во Человек",
    zh: "人数",
  },
  "booking.whatsapp_price": {
    es: "Precio Total",
    en: "Total Price",
    fr: "Prix Total",
    de: "Gesamtpreis",
    ru: "Общая Стоимость",
    zh: "总价格",
  },
  "booking.whatsapp_requests": {
    es: "Solicitudes",
    en: "Requests",
    fr: "Demandes",
    de: "Anfragen",
    ru: "Запросы",
    zh: "要求",
  },
  "booking.whatsapp_confirm": {
    es: "Por favor, confírmenme la disponibilidad y los próximos pasos.",
    en: "Please confirm availability and next steps.",
    fr: "Veuillez me confirmer la disponibilité et les prochaines étapes.",
    de: "Bitte bestätigen Sie mir die Verfügbarkeit und die nächsten Schritte.",
    ru: "Пожалуйста, подтвердите наличие и дальнейшие шаги.",
    zh: "请确认可用性和后续步骤。",
  },
  "booking.hero_title": {
    es: "Reserva Fácil y Rápida",
    en: "Easy and Quick Booking",
    fr: "Réservation Facile et Rapide",
    de: "Einfache und Schnelle Buchung",
    ru: "Легкое и Быстрое Бронирование",
    zh: "轻松快捷预订",
  },
  "booking.hero_subtitle": {
    es: "Tu aventura en Tenerife está a solo unos clics.",
    en: "Your Tenerife adventure is just a few clicks away.",
    fr: "Votre aventure à Tenerife n'est qu'à quelques clics.",
    de: "Dein Teneriffa-Abenteuer ist nur wenige Klicks entfernt.",
    ru: "Ваше приключение на Тенерифе всего в нескольких кликах.",
    zh: "您的特内里费冒险之旅仅需几次点击即可开始。",
  },
  "booking.hero_badge": {
    es: "Reserva Segura",
    en: "Secure Booking",
    fr: "Réservation Sécurisée",
    de: "Sichere Buchung",
    ru: "Безопасное Бронирование",
    zh: "安全预订",
  },
  "booking.form_title": {
    es: "Completa tus Datos de Reserva",
    en: "Complete Your Booking Details",
    fr: "Complétez Vos Coordonnées de Réservation",
    de: "Vervollständige Deine Buchungsdetails",
    ru: "Заполните Ваши Данные для Бронирования",
    zh: "填写您的预订详情",
  },
  "booking.form_subtitle": {
    es: "Selecciona tu excursión y prepara todo para una experiencia inolvidable.",
    en: "Select your excursion and prepare everything for an unforgettable experience.",
    fr: "Sélectionnez votre excursion et préparez tout pour une expérienceinoubliable.",
    de: "Wähle Deinen Ausflug und bereite alles für ein unvergessliches Erlebnis vor.",
    ru: "Выберите экскурсию и подготовьте все для незабываемого впечатления.",
    zh: "选择您的游览项目，为难忘的体验做好一切准备。",
  },
  "booking.select_excursion": {
    es: "Selecciona una Excursión",
    en: "Select an Excursion",
    fr: "Sélectionnez une Excursion",
    de: "Wähle einen Ausflug",
    ru: "Выберите Экскурсию",
    zh: "选择游览项目",
  },
  "booking.excursion_placeholder": {
    es: "Elige tu aventura...",
    en: "Choose your adventure...",
    fr: "Choisissez votre aventure...",
    de: "Wähle Dein Abenteuer...",
    ru: "Выберите свое приключение...",
    zh: "选择您的冒险...",
  },
  "booking.name": {
    es: "Nombre Completo",
    en: "Full Name",
    fr: "Nom Complet",
    de: "Vollständiger Name",
    ru: "Полное Имя",
    zh: "全名",
  },
  "booking.name_placeholder": {
    es: "Ej: María Pérez",
    en: "E.g., John Doe",
    fr: "Ex : Jean Dupont",
    de: "Z.B. Max Mustermann",
    ru: "Пример: Иван Иванов",
    zh: "例如：张三",
  },
  "booking.email": {
    es: "Correo Electrónico",
    en: "Email",
    fr: "Email",
    de: "Email",
    ru: "Электронная почта",
    zh: "电子邮件",
  },
  "booking.email_placeholder": {
    es: "tu@email.com",
    en: "your@email.com",
    fr: "votre@email.com",
    de: "deine@email.com",
    ru: "ваш@email.com",
    zh: "您的@email.com",
  },
  "booking.phone": {
    es: "Teléfono de Contacto",
    en: "Contact Phone",
    fr: "Téléphone de Contact",
    de: "Kontakttelefon",
    ru: "Контактный Телефон",
    zh: "联系电话",
  },
  "booking.phone_placeholder": {
    es: "+34 600 000 000",
    en: "+1 555 123 4567",
    fr: "+33 6 00 00 00 00",
    de: "+49 151 0000000",
    ru: "+7 900 000-00-00",
    zh: "+86 130 0000 0000",
  },
  "booking.date": {
    es: "Fecha de la Excursión",
    en: "Excursion Date",
    fr: "Date de l'Excursion",
    de: "Datum des Ausflugs",
    ru: "Дата Экскурсии",
    zh: "游览日期",
  },
  "booking.date_placeholder": {
    es: "Selecciona una fecha",
    en: "Select a date",
    fr: "Sélectionnez une date",
    de: "Wähle ein Datum",
    ru: "Выберите дату",
    zh: "选择日期",
  },
  "booking.people": {
    es: "Número de Personas",
    en: "Number of People",
    fr: "Nombre de Personnes",
    de: "Anzahl der Personen",
    ru: "Количество Человек",
    zh: "人数",
  },
  "booking.adults": {
    es: "Adultos",
    en: "Adults",
    fr: "Adultes",
    de: "Erwachsene",
    ru: "Взрослые",
    zh: "成人",
  },
  "booking.children": {
    es: "Niños (Menores de 12)",
    en: "Children (Under 12)",
    fr: "Enfants (Moins de 12 ans)",
    de: "Kinder (Unter 12)",
    ru: "Дети (до 12 лет)",
    zh: "儿童（12岁以下）",
  },
  "booking.message": {
    es: "Mensaje Adicional (Opcional)",
    en: "Additional Message (Optional)",
    fr: "Message Supplémentaire (Optionnel)",
    de: "Zusätzliche Nachricht (Optional)",
    ru: "Дополнительное Сообщение (Необязательно)",
    zh: "附加信息（可选）",
  },
  "booking.message_placeholder": {
    es: "Alergias, preferencias, etc.",
    en: "Allergies, preferences, etc.",
    fr: "Allergies, préférences, etc.",
    de: "Allergien, Vorlieben, etc.",
    ru: "Аллергии, предпочтения и т.д.",
    zh: "过敏、偏好等",
  },
  "booking.total_price": {
    es: "Precio Total Estimado",
    en: "Estimated Total Price",
    fr: "Prix Total Estimé",
    de: "Geschätzter Gesamtpreis",
    ru: "Ориентировочная Общая Стоимость",
    zh: "预计总价",
  },
  "booking.book_now": {
    es: "Reservar Ahora",
    en: "Book Now",
    fr: "Réserver Maintenant",
    de: "Jetzt Buchen",
    ru: "Забронировать Сейчас",
    zh: "立即预订",
  },
  "booking.sending": {
    es: "Enviando Reserva...",
    en: "Sending Booking...",
    fr: "Envoi de la Réservation...",
    de: "Buchung wird gesendet...",
    ru: "Отправка Бронирования...",
    zh: "正在发送预订...",
  },
  "booking.success_title": {
    es: "¡Reserva Confirmada!",
    en: "Booking Confirmed!",
    fr: "Réservation Confirmée !",
    de: "Buchung Bestätigt!",
    ru: "Бронирование Подтверждено!",
    zh: "预订已确认！",
  },
  "booking.success_message": {
    es: "Hemos recibido tu solicitud de reserva. Nos pondremos en contacto contigo pronto para finalizar los detalles. ¡Gracias!",
    en: "We have received your booking request. We will contact you soon to finalize the details. Thank you!",
    fr: "Nous avons reçu votre demande de réservation. Nous vous contacterons bientôt pour finaliser les détails. Merci !",
    de: "Wir haben Deine Buchungsanfrage erhalten. Wir werden Dich in Kürze kontaktieren, um die Details abzuschließen. Vielen Dank!",
    ru: "Мы получили Ваш запрос на бронирование. Мы свяжемся с Вами в ближайшее время для уточнения деталей. Спасибо!",
    zh: "我们已收到您的预订请求。我们将尽快与您联系以敲定细节。谢谢！",
  },
  "booking.error_title": {
    es: "Error en la Reserva",
    en: "Booking Error",
    fr: "Erreur de Réservation",
    de: "Buchungsfehler",
    ru: "Ошибка Бронирования",
    zh: "预订错误",
  },
  "booking.error_message": {
    es: "Hubo un problema al procesar tu reserva. Por favor, inténtalo de nuevo o contacta con nosotros directamente.",
    en: "There was a problem processing your booking. Please try again or contact us directly.",
    fr: "Un problème est survenu lors du traitement de votre réservation. Veuillez réessayer ou nous contacter directement.",
    de: "Bei der Bearbeitung Deiner Buchung ist ein Problem aufgetreten. Bitte versuche es erneut oder kontaktiere uns direkt.",
    ru: "При обработке Вашего бронирования произошла проблема. Пожалуйста, попробуйте еще раз или свяжитесь с нами напрямую.",
    zh: "处理您的预订时出现问题。请重试或直接与我们联系。",
  },
  "booking.back_home": {
    es: "Volver al Inicio",
    en: "Back to Home",
    fr: "Retour à l'Accueil",
    de: "Zurück zur Startseite",
    ru: "Вернуться на Главную",
    zh: "返回首页",
  },
  "booking.book_another": {
    es: "Reservar Otra Excursión",
    en: "Book Another Excursion",
    fr: "Réserver une Autre Excursion",
    de: "Weitere Exkursion Buchen",
    ru: "Забронировать Другую Экскурсию",
    zh: "预订其他游览",
  },
  "booking.why_book_with_us": {
    es: "¿Por Qué Reservar con Nosotros?",
    en: "Why Book With Us?",
    fr: "Pourquoi Réserver Avec Nous ?",
    de: "Warum bei Uns Buchen?",
    ru: "Почему Бронировать у Нас?",
    zh: "为什么选择我们预订？",
  },
  "booking.feature1_title": {
    es: "Confirmación Rápida",
    en: "Quick Confirmation",
    fr: "Confirmation Rapide",
    de: "Schnelle Bestätigung",
    ru: "Быстрое Подтверждение",
    zh: "快速确认",
  },
  "booking.feature1_desc": {
    es: "Recibe la confirmación de tu reserva al instante.",
    en: "Receive your booking confirmation instantly.",
    fr: "Recevez instantanément la confirmation de votre réservation.",
    de: "Erhalte Deine Buchungsbestätigung sofort.",
    ru: "Получите подтверждение бронирования мгновенно.",
    zh: "立即收到您的预订确认。",
  },
  "booking.feature2_title": {
    es: "Mejores Precios Garantizados",
    en: "Best Prices Guaranteed",
    fr: "Meilleurs Prix Garantis",
    de: "Bestpreisgarantie",
    ru: "Гарантия Лучшей Цены",
    zh: "保证最优惠价格",
  },
  "booking.feature2_desc": {
    es: "Ofrecemos tarifas competitivas para todas nuestras excursiones.",
    en: "We offer competitive rates for all our excursions.",
    fr: "Nous offrons des tarifs compétitifs pour toutes nos excursions.",
    de: "Wir bieten wettbewerbsfähige Preise für alle unsere Ausflüge.",
    ru: "Мы предлагаем конкурентоспособные цены на все наши экскурсии.",
    zh: "我们为所有游览项目提供有竞争力的价格。",
  },
  "booking.feature3_title": {
    es: "Soporte Experto",
    en: "Expert Support",
    fr: "Support Expert",
    de: "Expertenunterstützung",
    ru: "Экспертная Поддержка",
    zh: "专家支持",
  },
  "booking.feature3_desc": {
    es: "Nuestro equipo local está aquí para ayudarte en cada paso.",
    en: "Our local team is here to help you every step of the way.",
    fr: "Notre équipe locale est là pour vous aider à chaque étape.",
    de: "Unser lokales Team steht Dir bei jedem Schritt zur Seite.",
    ru: "Наша местная команда здесь, чтобы помочь вам на каждом этапе.",
    zh: "我们的本地团队随时为您提供帮助。",
  },
  "booking.quick_booking_title": {
    es: "Reserva Rápida de Excursión",
    en: "Quick Excursion Booking",
    fr: "Réservation Rapide d'Excursion",
    de: "Schnelle Ausflugsbuchung",
    ru: "Быстрое Бронирование Экскурсии",
    zh: "快速游览预订",
  },
  "booking.quick_booking_subtitle": {
    es: "Reserva tu aventura en Tenerife en pocos pasos.",
    en: "Book your Tenerife adventure in just a few steps.",
    fr: "Réservez votre aventure à Tenerife en quelques étapes seulement.",
    de: "Buche dein Teneriffa-Abenteuer in nur wenigen Schritten.",
    ru: "Забронируйте свое приключение на Тенерифе всего за несколько шагов.",
    zh: "只需几步即可预订您的特内里费冒险之旅。",
  },

  // Booking Modal
  "booking.modal.title": {
    es: "Reserva Rápida",
    en: "Quick Booking",
    fr: "Réservation Rapide",
    de: "Schnellbuchung",
    ru: "Быстрое Бронирование",
    zh: "快速预订",
  },
  "booking.modal.personal_data": {
    es: "Tus Datos",
    en: "Your Details",
    fr: "Vos Coordonnées",
    de: "Deine Daten",
    ru: "Ваши Данные",
    zh: "您的资料",
  },
  "booking.modal.full_name": {
    es: "Nombre completo",
    en: "Full name",
    fr: "Nom complet",
    de: "Vollständiger Name",
    ru: "Полное имя",
    zh: "全名",
  },
  "booking.modal.full_name_placeholder": {
    es: "Tu nombre aquí",
    en: "Your name here",
    fr: "Votre nom ici",
    de: "Dein Name hier",
    ru: "Ваше имя здесь",
    zh: "在此输入您的姓名",
  },
  "booking.modal.phone": {
    es: "Teléfono",
    en: "Phone",
    fr: "Téléphone",
    de: "Telefon",
    ru: "Телефон",
    zh: "电话",
  },
  "booking.modal.phone_placeholder": {
    es: "Tu número de teléfono",
    en: "Your phone number",
    fr: "Votre numéro de téléphone",
    de: "Deine Telefonnummer",
    ru: "Ваш номер телефона",
    zh: "您的电话号码",
  },
  "booking.modal.email": {
    es: "Email",
    en: "Email",
    fr: "Email",
    de: "Email",
    ru: "Электронная почта",
    zh: "电子邮件",
  },
  "booking.modal.email_placeholder": {
    es: "tu.email@ejemplo.com",
    en: "your.email@example.com",
    fr: "votre.email@exemple.com",
    de: "deine.email@beispiel.com",
    ru: "vash.email@primer.com",
    zh: "您的邮箱@example.com",
  },
  "booking.modal.booking_details": {
    es: "Detalles de la Reserva",
    en: "Booking Details",
    fr: "Détails de la Réservation",
    de: "Buchungsdetails",
    ru: "Детали Бронирования",
    zh: "预订详情",
  },
  "booking.modal.preferred_date": {
    es: "Fecha preferida",
    en: "Preferred date",
    fr: "Date préférée",
    de: "Bevorzugtes Datum",
    ru: "Предпочтительная дата",
    zh: "首选日期",
  },
  "booking.modal.number_of_people": {
    es: "Número de personas",
    en: "Number of people",
    fr: "Nombre de personnes",
    de: "Anzahl der Personen",
    ru: "Количество человек",
    zh: "人数",
  },
  "booking.modal.person": {
    es: "persona",
    en: "person",
    fr: "personne",
    de: "Person",
    ru: "человек",
    zh: "人",
  },
  "booking.modal.people": {
    es: "personas",
    en: "people",
    fr: "personnes",
    de: "Personen",
    ru: "человек", // Russian uses singular for count > 1 in some contexts, but "человек" is common for "people"
    zh: "人",
  },
  "booking.modal.special_requests": {
    es: "Solicitudes especiales",
    en: "Special requests",
    fr: "Demandes spéciales",
    de: "Sonderwünsche",
    ru: "Особые пожелания",
    zh: "特殊要求",
  },
  "booking.modal.special_requests_placeholder": {
    es: "Cualquier petición adicional...",
    en: "Any additional requests...",
    fr: "Toute demande supplémentaire...",
    de: "Zusätzliche Anfragen...",
    ru: "Любые дополнительные запросы...",
    zh: "任何其他要求...",
  },
  "booking.modal.price_summary": {
    es: "Resumen del Precio",
    en: "Price Summary",
    fr: "Résumé du Prix",
    de: "Preisübersicht",
    ru: "Сводка Цен",
    zh: "价格摘要",
  },
  "booking.modal.price_per_person": {
    es: "Precio por persona",
    en: "Price per person",
    fr: "Prix par personne",
    de: "Preis pro Person",
    ru: "Цена за человека",
    zh: "每人价格",
  },
  "booking.modal.number_of_people_summary": {
    es: "Nº de personas",
    en: "No. of people",
    fr: "Nº de personnes",
    de: "Anzahl Personen",
    ru: "Кол-во человек",
    zh: "人数",
  },
  "booking.modal.estimated_total": {
    es: "Total Estimado",
    en: "Estimated Total",
    fr: "Total Estimé",
    de: "Geschätzte Gesamtsumme",
    ru: "Ориентировочная Сумма",
    zh: "预计总额",
  },
  "booking.modal.cancel": {
    es: "Cancelar",
    en: "Cancel",
    fr: "Annuler",
    de: "Abbrechen",
    ru: "Отмена",
    zh: "取消",
  },
  "booking.modal.continue_whatsapp": {
    es: "Continuar por WhatsApp",
    en: "Continue via WhatsApp",
    fr: "Continuer via WhatsApp",
    de: "Weiter über WhatsApp",
    ru: "Продолжить через WhatsApp",
    zh: "通过WhatsApp继续",
  },
  "booking.modal.sending": {
    es: "Enviando...",
    en: "Sending...",
    fr: "Envoi...",
    de: "Senden...",
    ru: "Отправка...",
    zh: "发送中...",
  },
  "booking.modal.whatsapp_info": {
    es: "Serás redirigido a WhatsApp para confirmar tu reserva.",
    en: "You will be redirected to WhatsApp to confirm your booking.",
    fr: "Vous serez redirigé vers WhatsApp pour confirmer votre réservation.",
    de: "Du wirst zu WhatsApp weitergeleitet, um deine Buchung zu bestätigen.",
    ru: "Вы будете перенаправлены в WhatsApp для подтверждения бронирования.",
    zh: "您将被重定向到WhatsApp以确认您的预订。",
  },
}

// Función para detectar idioma del navegador automáticamente
const detectBrowserLanguage = (): Language => {
  if (typeof window === "undefined") return "es"

  const browserLanguages = navigator.languages || [navigator.language]
  const supportedLanguages: Language[] = ["es", "en", "fr", "de", "ru", "zh"]

  for (const browserLang of browserLanguages) {
    const langCode = browserLang.split("-")[0].toLowerCase() as Language
    if (supportedLanguages.includes(langCode)) {
      return langCode
    }
  }

  return "es" // Fallback a español
}

export const LanguageContext = createContext<{
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, replacements?: { [key: string]: string | number }) => string
}>({
  language: "es",
  setLanguage: () => {},
  t: (key: string) => key,
})

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("es")

  useEffect(() => {
    const storedLanguage = localStorage.getItem("language") as Language | null

    if (storedLanguage) {
      setLanguage(storedLanguage)
    } else {
      const detectedLanguage = detectBrowserLanguage()
      setLanguage(detectedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("language", language)
    document.documentElement.lang = language // Update lang attribute of HTML tag
  }, [language])

  const t = (key: string, replacements?: { [key: string]: string | number }): string => {
    let translation = key

    const langTranslations = translations[key]

    if (langTranslations && typeof langTranslations[language] !== "undefined") {
      translation = langTranslations[language]
    } else {
      const keys = key.split(".")
      let current: any = translations
      let found = true
      for (const k of keys) {
        if (current && typeof current === "object" && k in current) {
          current = current[k]
        } else {
          current = null
          found = false
          break
        }
      }
      if (found && current && typeof current === "object" && typeof current[language] !== "undefined") {
        translation = current[language]
      } else if (found && typeof current === "string") {
        translation = current
      } else {
        if (process.env.NODE_ENV === "development") {
          console.warn(`Missing translation for key: "${key}" in language: "${language}"`)
        }
      }
    }

    if (replacements) {
      Object.keys(replacements).forEach((placeholder) => {
        const regex = new RegExp(`\\{${placeholder}\\}`, "g")
        translation = translation.replace(regex, String(replacements[placeholder]))
      })
    }
    return translation
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
