"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "es" | "en" | "de"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.excursions": "Excursiones",
    "nav.contact": "Contacto",
    "nav.about": "Sobre Nosotros",
    "nav.booking": "Reservas",
    "nav.language": "Idioma",

    // Hero Section
    "hero.title": "Vive Tenerife",
    "hero.subtitle": "de forma extraordinaria",
    "hero.description": "¿Listo para vivir experiencias que cambiarán tu perspectiva de Tenerife para siempre?",
    "hero.description2": "Tu próxima gran aventura está a solo un mensaje de distancia.",
    "hero.search": "Buscar excursiones...",
    "hero.stats.excursions": "Excursiones",
    "hero.stats.rating": "Valoración Media",
    "hero.stats.satisfaction": "Satisfacción",

    // Featured Excursions
    "featured.title": "Aventuras que Enamoran",
    "featured.subtitle": "Cada experiencia está diseñada para crear recuerdos que durarán toda la vida",
    "featured.book": "Reservar por WhatsApp",
    "featured.from": "Desde",
    "featured.badge": "Experiencias Más Valoradas",
    "featured.view_all": "Descubrir Todas las Aventuras",
    "featured.whatsapp_interest": "Hola! Me interesa la excursión",
    "featured.whatsapp_info": "¿Podrían darme más información?",
    "featured.teide_stars": "Teide y Estrellas",
    "featured.whale_watching": "Avistamiento Ballenas",
    "featured.anaga_hiking": "Senderismo Anaga",
    "featured.view_all_short": "Ver Todas",

    // Excursions Page
    "excursions.title": "Todas Nuestras",
    "excursions.title2": "Experiencias",
    "excursions.subtitle":
      "Descubre la magia de Tenerife con nuestras excursiones cuidadosamente seleccionadas. Desde aventuras en la naturaleza hasta experiencias gastronómicas únicas.",
    "excursions.filters": "Filtros y Búsqueda",
    "excursions.search_placeholder": "Buscar por nombre o descripción...",
    "excursions.all_categories": "Todas las categorías",
    "excursions.all_prices": "Todos los precios",
    "excursions.price_low": "Menos de €50",
    "excursions.price_medium": "€50 - €80",
    "excursions.price_high": "Más de €80",
    "excursions.sort_featured": "Destacadas",
    "excursions.sort_price_low": "Precio: Menor a Mayor",
    "excursions.sort_price_high": "Precio: Mayor a Menor",
    "excursions.sort_name": "Nombre A-Z",
    "excursions.found": "Experiencia Encontrada",
    "excursions.found_plural": "Experiencias Encontradas",
    "excursions.showing_all": "Mostrando todas nuestras experiencias disponibles",
    "excursions.filtered_from": "Filtrado de",
    "excursions.total_experiences": "experiencias totales",
    "excursions.no_results": "No se encontraron excursiones",
    "excursions.no_results_text":
      "No encontramos excursiones que coincidan con tus filtros. Prueba ajustando los criterios de búsqueda.",
    "excursions.view_all": "Ver todas las excursiones",
    "excursions.clear_filters": "Limpiar todos",
    "excursions.custom_experience": "¿No encuentras lo que buscas?",
    "excursions.custom_text":
      "Nuestro equipo puede crear experiencias personalizadas según tus intereses. Contáctanos y diseñaremos la aventura perfecta para ti.",
    "excursions.contact_custom": "Contactar para Experiencia Personalizada",
    "excursions.search_label": "Búsqueda",

    // Common
    "common.loading": "Cargando...",
    "common.error": "Error al cargar datos",
    "common.success": "Éxito",
    "common.duration": "Duración",
    "common.price": "Precio",
    "common.category": "Categoría",
    "common.rating": "Valoración",
    "common.reviews": "reseñas",
    "common.free_cancellation": "Cancelación gratuita",
    "common.small_group": "Grupo reducido",
    "common.all_ratings": "Todas con valoración 4.8+ ⭐",
    "common.preparing": "Preparando tu aventura...",
    "common.loading_experiences": "Cargando experiencias...",

    // CTA Sections
    "cta.adventure_title": "Comienza tu",
    "cta.adventure_title2": "Aventura Perfecta",
    "cta.adventure_text": "Empieza esta aventura con nosotros y descubre la cara más auténtica de la isla",
    "cta.adventure_text2": "Tu historia extraordinaria comienza con un solo clic.",
    "cta.book_now": "Reservar Ahora",
    "cta.more_info": "Más Información",
    "cta.ready_title": "¿Listo Para Tu Próxima Aventura?",
    "cta.ready_text":
      "Nuestro equipo está esperando para ayudarte a crear recuerdos inolvidables en Tenerife. ¡Tu aventura perfecta está a solo un mensaje de distancia!",
    "cta.contact_now": "Contactar Ahora",
    "cta.view_excursions": "Ver Excursiones",

    // Categories
    "category.naturaleza": "Naturaleza",
    "category.marina": "Marina",
    "category.senderismo": "Senderismo",
    "category.gastronomia": "Gastronomía",
    "category.paisajes": "Paisajes",
    "category.familia": "Familia",
    "category.aventura": "Aventura",
    "category.cultural": "Cultural",

    // Excursion Details
    "excursion.back_to_excursions": "Volver a Excursiones",
    "excursion.description": "Descripción",
    "excursion.itinerary": "Itinerario",
    "excursion.included": "Incluido",
    "excursion.what_to_bring": "Qué traer",
    "excursion.per_person": "por persona",
    "excursion.hours": "horas",
    "excursion.max_capacity": "Capacidad máxima",
    "excursion.people": "personas",
    "excursion.difficulty": "Dificultad",
    "excursion.free_cancel": "Cancelación gratuita hasta 24h antes",
    "excursion.important_info": "Información Importante",
    "excursion.confirmation_immediate": "Confirmación inmediata",
    "excursion.mobile_ticket": "Ticket móvil",
    "excursion.free_cancellation": "Cancelación gratuita",
    "excursion.pickup_included": "Recogida incluida",

    // Gallery
    "gallery.badge": "Galería de Fotos",
    "gallery.title": "Galería de Aventuras",
    "gallery.subtitle": "Descubre los momentos más emocionantes de nuestras excursiones",

    // About page
    "about.title": "Sobre Nosotros",
    "about.subtitle": "Conoce nuestro equipo",
    "about.description": "Somos especialistas en crear experiencias únicas en Tenerife",

    // Contact page
    "contact.title": "Contacto",
    "contact.subtitle": "Ponte en contacto con nosotros",
    "contact.form.name": "Nombre",
    "contact.form.email": "Email",
    "contact.form.message": "Mensaje",
    "contact.form.send": "Enviar",

    // Booking page
    "booking.title": "Reservas",
    "booking.subtitle": "Reserva tu aventura",
    "booking.form.date": "Fecha",
    "booking.form.people": "Número de personas",
    "booking.form.excursion": "Excursión",

    // Admin pages
    "admin.title": "Administración",
    "admin.categories": "Gestión de Categorías",
    "admin.excursions": "Gestión de Excursiones",
    "admin.add_category": "Añadir Categoría",
    "admin.edit_category": "Editar Categoría",
    "admin.add_excursion": "Añadir Excursión",
    "admin.edit_excursion": "Editar Excursión",

    // Form labels
    "form.title": "Título",
    "form.description": "Descripción",
    "form.price": "Precio",
    "form.duration": "Duración",
    "form.capacity": "Capacidad",
    "form.difficulty": "Dificultad",
    "form.category": "Categoría",
    "form.save": "Guardar",
    "form.cancel": "Cancelar",
    "form.delete": "Eliminar",
    "form.edit": "Editar",

    // Footer
    "footer.company_description": "Especialistas en crear experiencias únicas en Tenerife desde 2015",
    "footer.quick_links": "Enlaces Rápidos",
    "footer.contact_info": "Información de Contacto",
    "footer.newsletter": "Newsletter",
    "footer.newsletter_text": "Recibe ofertas especiales y novedades",
    "footer.subscribe": "Suscribirse",
    "footer.copyright": "© 2024 TenerifeParadiseTours. Todos los derechos reservados.",
    "footer.designed_by": "Diseñado por",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos y Condiciones",
    "footer.faq": "Preguntas Frecuentes",

    // About page - Stats and Story
    "about.hero_badge": "Nuestra Historia",
    "about.stat_excursions": "Excursiones",
    "about.stat_rating": "Valoración",
    "about.achievements": "Nuestros Logros",
    "about.achievements_subtitle": "Números que hablan por sí solos",
    "about.story_badge": "Nuestra Historia",
    "about.story_title": "Más de una Década Creando Recuerdos",
    "about.story_p1":
      "Comenzamos en 2015 con una simple misión: mostrar la verdadera belleza de Tenerife a través de experiencias auténticas y memorables.",
    "about.story_p2":
      "Desde entonces, hemos guiado a miles de visitantes por los rincones más espectaculares de la isla, desde las cumbres del Teide hasta las costas volcánicas.",
    "about.story_p3":
      "Nuestro equipo de guías locales comparte la pasión por esta tierra única, garantizando que cada excursión sea una ventana a la cultura y naturaleza canaria.",
    "about.team_caption": "Nuestro equipo de guías expertos",
    "about.team_subtitle": "Apasionados por Tenerife",
    "about.pillars_title": "Nuestros Pilares",
    "about.pillars_subtitle": "Los valores que nos definen",
    "about.mission": "Misión",
    "about.mission_text":
      "Crear experiencias turísticas auténticas que conecten a nuestros visitantes con la esencia de Tenerife.",
    "about.vision": "Visión",
    "about.vision_text": "Ser la empresa líder en turismo sostenible y experiencial en las Islas Canarias.",
    "about.values": "Valores",
    "about.values_text":
      "Pasión, respeto por el medio ambiente, calidad en el servicio y compromiso con la comunidad local.",
    "about.value_passion_title": "Pasión por Tenerife",
    "about.value_passion_desc": "Cada excursión refleja nuestro amor profundo por esta isla extraordinaria",
    "about.value_experience_title": "Experiencia Local",
    "about.value_experience_desc": "Más de 10 años compartiendo los secretos mejor guardados de Tenerife",
    "about.value_security_title": "Seguridad Garantizada",
    "about.value_security_desc": "Protocolos de seguridad certificados para tu tranquilidad total",
    "about.value_quality_title": "Calidad Premium",
    "about.value_quality_desc": "Servicios de alta calidad con atención personalizada en cada detalle",
    "about.certifications_title": "Certificaciones y Reconocimientos",
    "about.certifications_subtitle": "Avalados por las mejores instituciones",
    "about.cert_sustainable_tourism": "Turismo Sostenible Certificado",
    "about.cert_official_guides": "Guías Oficiales Autorizados",
    "about.cert_responsible_company": "Empresa Responsable",
    "about.cert_tripadvisor_excellence": "Certificado de Excelencia TripAdvisor",
    "about.cta_title": "¿Listo para Descubrir Tenerife?",
    "about.cta_description": "Únete a miles de viajeros que ya han vivido experiencias inolvidables con nosotros",
    "about.cta_view_excursions": "Ver Excursiones",
    "about.cta_contact": "Contactar",

    // Contact page
    "contact.hero_badge": "Contacto Directo",
    "contact.hero_subtitle": "Tu próxima aventura comienza aquí",
    "contact.subtitle_extended": "Estamos aquí para ayudarte a planificar la experiencia perfecta en Tenerife",
    "contact.immediate_contact": "Contacto Inmediato",
    "contact.quick_response_question": "¿Necesitas una respuesta rápida?",
    "contact.open_whatsapp": "Abrir WhatsApp",
    "contact.attention_schedule": "Horario de Atención",
    "contact.schedule_text": "Lunes a Domingo: 8:00 - 22:00 (Hora local)",
    "contact.why_choose_us": "¿Por qué elegirnos?",
    "contact.faq": "Preguntas Frecuentes",
    "contact.how_to_book": "¿Cómo puedo reservar?",
    "contact.how_to_book_answer": "Puedes reservar por WhatsApp, teléfono o a través de nuestro formulario online",
    "contact.what_includes": "¿Qué incluyen las excursiones?",
    "contact.what_includes_answer": "Transporte, guía, seguro y todo lo especificado en cada excursión",
    "contact.group_discounts": "¿Hay descuentos para grupos?",
    "contact.group_discounts_answer": "Sí, ofrecemos descuentos especiales para grupos de 6 o más personas",
    "contact.form_title": "Envíanos un Mensaje",
    "contact.form_subtitle": "Te responderemos en menos de 2 horas",
    "contact.success_title": "¡Mensaje Enviado!",
    "contact.success_message": "Hemos recibido tu mensaje y te responderemos muy pronto. ¡Gracias por contactarnos!",
    "contact.send_another": "Enviar Otro Mensaje",
    "contact.whatsapp_contact": "Contactar por WhatsApp",
    "contact.name": "Nombre completo",
    "contact.email": "Correo electrónico",
    "contact.phone": "Teléfono (opcional)",
    "contact.message": "Mensaje",
    "contact.send": "Enviar Mensaje",

    // Contact info
    "contact_info.phone": "Teléfono",
    "contact_info.whatsapp": "WhatsApp",
    "contact_info.email": "Email",
    "contact_info.location": "Ubicación",
    "contact_info.available": "Disponible 24/7",
    "contact_info.immediate_response": "Respuesta inmediata",
    "contact_info.response_time": "Respuesta en 2 horas",
    "contact_info.canary_islands": "Islas Canarias, España",

    // Trust indicators
    "trust.guaranteed_response": "Respuesta Garantizada",
    "trust.guaranteed_text": "Te respondemos en menos de 2 horas, siempre",
    "trust.personal_attention": "Atención Personal",
    "trust.personal_text": "Cada cliente recibe un trato personalizado y único",
    "trust.multilingual": "Multiidioma",
    "trust.multilingual_text": "Atendemos en español, inglés y alemán",
    "trust.service_passion": "Pasión por el Servicio",
    "trust.service_text": "Más de 10 años creando experiencias inolvidables",

    // Booking page
    "booking.hero_badge": "Reserva Fácil y Segura",
    "booking.subtitle2": "Tu próxima gran aventura está a solo un mensaje de distancia.",
    "booking.trust_confirmation": "Confirmación inmediata",
    "booking.trust_cancellation": "Cancelación gratuita",
    "booking.trust_support": "Soporte 24/7",
    "booking.form_title": "Formulario de Reserva",
    "booking.personal_info": "Información Personal",
    "booking.excursion_details": "Detalles de la Excursión",
    "booking.select_excursion": "Selecciona una excursión",
    "booking.excursion_placeholder": "Elige tu aventura perfecta...",
    "booking.premium_label": "Premium",
    "booking.date": "Fecha preferida",
    "booking.people": "Número de personas",
    "booking.people_count": "persona(s)",
    "booking.requests": "Solicitudes especiales",
    "booking.requests_placeholder": "¿Alguna solicitud especial? (dieta, movilidad, etc.)",
    "booking.submit": "Reservar por WhatsApp",
    "booking.processing": "Procesando...",
    "booking.summary": "Resumen de Reserva",
    "booking.duration_label": "Duración",
    "booking.category_label": "Categoría",
    "booking.rating_label": "Valoración",
    "booking.reviews_label": "reseñas",
    "booking.price_per_person": "Precio por persona",
    "booking.people_summary": "Personas",
    "booking.total_estimated": "Total Estimado",
    "booking.included_price": "Incluido en el precio",
    "booking.transport": "Transporte",
    "booking.guide": "Guía profesional",
    "booking.insurance": "Seguro",
    "booking.photos": "Fotos del recorrido",
    "booking.select_excursion_message": "Selecciona una excursión para ver el resumen",
    "booking.select_excursion_subtitle": "Elige tu aventura perfecta arriba",
    "booking.why_choose_us": "¿Por qué elegirnos?",
    "booking.trust_guides": "Guías locales expertos",
    "booking.trust_groups": "Grupos reducidos",
    "booking.feature_confirmation": "Confirmación Inmediata",
    "booking.feature_confirmation_desc": "Recibe confirmación al instante por WhatsApp",
    "booking.feature_payment": "Pago Flexible",
    "booking.feature_payment_desc": "Paga en efectivo el día de la excursión",
    "booking.feature_experience": "Experiencia Garantizada",
    "booking.feature_experience_desc": "Más de 4.9/5 estrellas en todas nuestras excursiones",
    "booking.whatsapp_greeting": "Nueva reserva desde la web",
    "booking.whatsapp_excursion": "Excursión",
    "booking.whatsapp_date": "Fecha preferida",
    "booking.whatsapp_people": "Personas",
    "booking.whatsapp_price": "Precio total estimado",
    "booking.whatsapp_requests": "Solicitudes especiales",
    "booking.whatsapp_confirm": "¡Esperamos confirmar tu reserva pronto!",
    "booking.success_title": "¡Reserva Enviada!",
    "booking.success_message": "Te redirigimos a WhatsApp para confirmar tu reserva...",
    "booking.error_message": "Error al procesar la reserva. Inténtalo de nuevo.",
    "booking.name_placeholder": "Tu nombre completo",
    "booking.email_placeholder": "tu@email.com",

    // Privacy Policy
    "privacy.title": "Política de Privacidad",
    "privacy.subtitle": "Protección de tus datos personales",
    "privacy.intro.title": "Compromiso con tu Privacidad",
    "privacy.intro.content":
      "En TenerifeParadiseTours respetamos y protegemos la privacidad de nuestros usuarios. Esta política explica cómo recopilamos, usamos y protegemos tu información personal.",
    "privacy.section1.title": "Información que Recopilamos",
    "privacy.section1.content1": "Datos de contacto: nombre, email, teléfono",
    "privacy.section1.content2": "Información de reservas: fechas, preferencias, solicitudes especiales",
    "privacy.section1.content3": "Datos de navegación: cookies, IP, dispositivo utilizado",
    "privacy.section1.content4": "Información voluntaria: comentarios, valoraciones, fotos",
    "privacy.section2.title": "Cómo Usamos tu Información",
    "privacy.section2.content1": "Procesar y confirmar tus reservas de excursiones",
    "privacy.section2.content2": "Comunicarnos contigo sobre tu reserva y servicios",
    "privacy.section2.content3": "Mejorar nuestros servicios y experiencia de usuario",
    "privacy.section2.content4": "Enviar ofertas especiales (solo si das tu consentimiento)",
    "privacy.section3.title": "Protección de Datos",
    "privacy.section3.content1": "Utilizamos encriptación SSL para proteger tus datos",
    "privacy.section3.content2": "Acceso limitado solo a personal autorizado",
    "privacy.section3.content3": "Servidores seguros con copias de seguridad regulares",
    "privacy.section3.content4": "Cumplimiento estricto del RGPD europeo",
    "privacy.section4.title": "Tus Derechos",
    "privacy.section4.content1": "Acceder a tus datos personales almacenados",
    "privacy.section4.content2": "Rectificar información incorrecta o incompleta",
    "privacy.section4.content3": "Solicitar la eliminación de tus datos",
    "privacy.section4.content4": "Oponerte al procesamiento de tus datos",
    "privacy.section5.title": "Cookies y Tecnologías",
    "privacy.section5.content1": "Cookies esenciales para el funcionamiento del sitio",
    "privacy.section5.content2": "Cookies analíticas para mejorar la experiencia",
    "privacy.section5.content3": "Puedes desactivar las cookies en tu navegador",
    "privacy.section5.content4": "Algunas funciones pueden verse limitadas sin cookies",
    "privacy.section6.title": "Contacto y Consultas",
    "privacy.section6.content1": "Para cualquier consulta sobre privacidad, contáctanos",
    "privacy.section6.content2": "Responderemos en un plazo máximo de 72 horas",
    "privacy.section6.content3": "Tienes derecho a presentar una reclamación ante la autoridad competente",
    "privacy.section6.content4": "Actualizamos esta política periódicamente",
    "privacy.contact_info.title": "Información de Contacto",
    "privacy.contact_info.company": "Empresa",
    "privacy.contact_info.company_name": "TenerifeParadiseTours S.L.",
    "privacy.contact_info.cif": "CIF",
    "privacy.contact_info.cif_number": "B-12345678",
    "privacy.contact_info.address": "Dirección",
    "privacy.contact_info.address_text": "Santa Cruz de Tenerife, España",
    "privacy.contact_info.email": "Email",
    "privacy.contact_info.email_address": "Tenerifeparadisetoursandexcursions@hotmail.com",
    "privacy.contact_info.phone": "Teléfono",
    "privacy.contact_info.phone_number": "+34 617 30 39 29",
    "privacy.buttons.understood": "Entendido",
    "privacy.buttons.print": "Imprimir",

    // Terms and Conditions
    "terms.title": "Términos y Condiciones",
    "terms.subtitle": "Condiciones de uso de nuestros servicios",
    "terms.intro.title": "Condiciones Generales",
    "terms.intro.content":
      "Estos términos y condiciones regulan el uso de nuestros servicios turísticos. Al realizar una reserva, aceptas estas condiciones.",
    "terms.section1.title": "Servicios Ofrecidos",
    "terms.section1.content1": "Excursiones guiadas por Tenerife con guías profesionales",
    "terms.section1.content2": "Transporte incluido desde puntos de recogida establecidos",
    "terms.section1.content3": "Seguro de responsabilidad civil incluido",
    "terms.section1.content4": "Material necesario para las actividades cuando aplique",
    "terms.section2.title": "Reservas y Confirmación",
    "terms.section2.content1": "Las reservas se confirman por WhatsApp o email",
    "terms.section2.content2": "Se requiere confirmación 24 horas antes de la excursión",
    "terms.section2.content3": "Punto de encuentro y hora se comunican al confirmar",
    "terms.section2.content4": "Cambios de fecha sujetos a disponibilidad",
    "terms.section3.title": "Pagos y Precios",
    "terms.section3.content1": "Pago en efectivo el día de la excursión",
    "terms.section3.content2": "Precios incluyen todos los servicios especificados",
    "terms.section3.content3": "Descuentos para grupos de 6 o más personas",
    "terms.section3.content4": "Los precios pueden cambiar sin previo aviso",
    "terms.section4.title": "Cancelaciones",
    "terms.section4.content1": "Cancelación gratuita hasta 24 horas antes",
    "terms.section4.content2": "Cancelaciones por mal tiempo: reprogramación o reembolso",
    "terms.section4.content3": "No-show: no hay reembolso",
    "terms.section4.content4": "Cancelaciones de último minuto: sujetas a penalización",
    "terms.section5.title": "Responsabilidades",
    "terms.section5.content1": "Los participantes deben seguir las instrucciones del guía",
    "terms.section5.content2": "Informar sobre condiciones médicas relevantes",
    "terms.section5.content3": "La empresa no se responsabiliza por objetos perdidos",
    "terms.section5.content4": "Seguro médico personal recomendado",
    "terms.section6.title": "Condiciones Especiales",
    "terms.section6.content1": "Edad mínima y máxima según la excursión",
    "terms.section6.content2": "Nivel de forma física requerido especificado",
    "terms.section6.content3": "Condiciones meteorológicas pueden afectar la ruta",
    "terms.section6.content4": "Derecho de admisión reservado",
    "terms.important_notice.title": "Aviso Importante",
    "terms.important_notice.content":
      "Estas condiciones pueden modificarse. La versión vigente es la publicada en nuestra web.",
    "terms.legal_info.title": "Información Legal",
    "terms.buttons.accept": "Aceptar",
    "terms.buttons.print": "Imprimir",

    // FAQ
    "faq.title": "Preguntas Frecuentes",
    "faq.subtitle": "Respuestas a las dudas más comunes",
    "faq.intro.title": "¿Tienes alguna duda?",
    "faq.intro.content":
      "Aquí encontrarás respuestas a las preguntas más frecuentes sobre nuestras excursiones y servicios.",
    "faq.category1.title": "Reservas y Confirmación",
    "faq.category1.q1.question": "¿Cómo puedo reservar una excursión?",
    "faq.category1.q1.answer":
      "Puedes reservar a través de WhatsApp, nuestro formulario web o llamando directamente. Te confirmaremos todos los detalles.",
    "faq.category1.q2.question": "¿Cuándo recibo la confirmación?",
    "faq.category1.q2.answer":
      "Recibirás confirmación inmediata por WhatsApp con todos los detalles: punto de encuentro, hora y qué llevar.",
    "faq.category1.q3.question": "¿Puedo cambiar la fecha de mi reserva?",
    "faq.category1.q3.answer":
      "Sí, puedes cambiar la fecha sin coste adicional hasta 24 horas antes, sujeto a disponibilidad.",
    "faq.category2.title": "Pagos y Precios",
    "faq.category2.q1.question": "¿Cuándo debo pagar?",
    "faq.category2.q1.answer":
      "El pago se realiza en efectivo el día de la excursión, directamente al guía antes de comenzar.",
    "faq.category2.q2.question": "¿Qué incluye el precio?",
    "faq.category2.q2.answer":
      "Incluye transporte, guía profesional, seguro y todo lo especificado en cada excursión. Sin costes ocultos.",
    "faq.category2.q3.question": "¿Hay descuentos para grupos?",
    "faq.category2.q3.answer":
      "Sí, ofrecemos descuentos especiales para grupos de 6 o más personas. Contáctanos para más detalles.",
    "faq.category3.title": "Durante la Excursión",
    "faq.category3.q1.question": "¿Qué debo llevar?",
    "faq.category3.q1.answer":
      "Te enviaremos una lista específica al confirmar. Generalmente: agua, protector solar, calzado cómodo y cámara.",
    "faq.category3.q2.question": "¿Qué pasa si llueve?",
    "faq.category3.q2.answer":
      "Monitoreamos el clima constantemente. Si las condiciones no son seguras, reprogramamos o reembolsamos.",
    "faq.category3.q3.question": "¿Cuántas personas van por grupo?",
    "faq.category3.q3.answer":
      "Mantenemos grupos pequeños (máximo 8 personas) para una experiencia más personalizada y auténtica.",
    "faq.category4.title": "Logística y Transporte",
    "faq.category4.q1.question": "¿Dónde es el punto de encuentro?",
    "faq.category4.q1.answer":
      "Tenemos varios puntos de recogida. Te asignaremos el más conveniente según tu ubicación al confirmar.",
    "faq.category4.q2.question": "¿Recogen en mi hotel?",
    "faq.category4.q2.answer":
      "Sí, ofrecemos recogida en la mayoría de hoteles de las zonas turísticas principales de Tenerife.",
    "faq.category4.q3.question": "¿Qué tipo de vehículos usan?",
    "faq.category4.q3.answer":
      "Utilizamos vehículos cómodos y seguros, adaptados al tipo de excursión: minibuses, 4x4 o vehículos especializados.",
    "faq.contact.title": "¿No encuentras tu respuesta?",
    "faq.contact.content": "Nuestro equipo está disponible para resolver cualquier duda específica que tengas.",
    "faq.contact.whatsapp": "Contactar por WhatsApp",
    "faq.contact.schedule": "Ver Horarios",
    "faq.buttons.close": "Cerrar",
    "faq.buttons.print": "Imprimir",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.excursions": "Excursions",
    "nav.contact": "Contact",
    "nav.about": "About Us",
    "nav.booking": "Booking",
    "nav.language": "Language",

    // Hero Section
    "hero.title": "Experience Tenerife",
    "hero.subtitle": "in an extraordinary way",
    "hero.description": "Ready to live experiences that will change your perspective of Tenerife forever?",
    "hero.description2": "Your next great adventure is just one message away.",
    "hero.search": "Search excursions...",
    "hero.stats.excursions": "Excursions",
    "hero.stats.rating": "Average Rating",
    "hero.stats.satisfaction": "Satisfaction",

    // Featured Excursions
    "featured.title": "Adventures that Captivate",
    "featured.subtitle": "Each experience is designed to create memories that will last a lifetime",
    "featured.book": "Book via WhatsApp",
    "featured.from": "From",
    "featured.badge": "Most Valued Experiences",
    "featured.view_all": "Discover All Adventures",
    "featured.whatsapp_interest": "Hello! I'm interested in the excursion",
    "featured.whatsapp_info": "Could you give me more information?",
    "featured.teide_stars": "Teide & Stars",
    "featured.whale_watching": "Whale Watching",
    "featured.anaga_hiking": "Anaga Hiking",
    "featured.view_all_short": "View All",

    // Excursions Page
    "excursions.title": "All Our",
    "excursions.title2": "Experiences",
    "excursions.subtitle":
      "Discover the magic of Tenerife with our carefully selected excursions. From nature adventures to unique gastronomic experiences.",
    "excursions.filters": "Filters and Search",
    "excursions.search_placeholder": "Search by name or description...",
    "excursions.all_categories": "All categories",
    "excursions.all_prices": "All prices",
    "excursions.price_low": "Less than €50",
    "excursions.price_medium": "€50 - €80",
    "excursions.price_high": "More than €80",
    "excursions.sort_featured": "Featured",
    "excursions.sort_price_low": "Price: Low to High",
    "excursions.sort_price_high": "Price: High to Low",
    "excursions.sort_name": "Name A-Z",
    "excursions.found": "Experience Found",
    "excursions.found_plural": "Experiences Found",
    "excursions.showing_all": "Showing all our available experiences",
    "excursions.filtered_from": "Filtered from",
    "excursions.total_experiences": "total experiences",
    "excursions.no_results": "No excursions found",
    "excursions.no_results_text":
      "We couldn't find excursions matching your filters. Try adjusting your search criteria.",
    "excursions.view_all": "View all excursions",
    "excursions.clear_filters": "Clear all",
    "excursions.custom_experience": "Can't find what you're looking for?",
    "excursions.custom_text":
      "Our team can create personalized experiences according to your interests. Contact us and we'll design the perfect adventure for you.",
    "excursions.contact_custom": "Contact for Custom Experience",
    "excursions.search_label": "Search",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error loading data",
    "common.success": "Success",
    "common.duration": "Duration",
    "common.price": "Price",
    "common.category": "Category",
    "common.rating": "Rating",
    "common.reviews": "reviews",
    "common.free_cancellation": "Free cancellation",
    "common.small_group": "Small group",
    "common.all_ratings": "All with 4.8+ rating ⭐",
    "common.preparing": "Preparing your adventure...",
    "common.loading_experiences": "Loading experiences...",

    // CTA Sections
    "cta.adventure_title": "Start your",
    "cta.adventure_title2": "Perfect Adventure",
    "cta.adventure_text": "Start this adventure with us and discover the most authentic face of the island",
    "cta.adventure_text2": "Your extraordinary story begins with a single click.",
    "cta.book_now": "Book Now",
    "cta.more_info": "More Information",
    "cta.ready_title": "Ready For Your Next Adventure?",
    "cta.ready_text":
      "Our team is waiting to help you create unforgettable memories in Tenerife. Your perfect adventure is just one message away!",
    "cta.contact_now": "Contact Now",
    "cta.view_excursions": "View Excursions",

    // Categories
    "category.naturaleza": "Nature",
    "category.marina": "Marine",
    "category.senderismo": "Hiking",
    "category.gastronomia": "Gastronomy",
    "category.paisajes": "Landscapes",
    "category.familia": "Family",
    "category.aventura": "Adventure",
    "category.cultural": "Cultural",

    // Excursion Details
    "excursion.back_to_excursions": "Back to Excursions",
    "excursion.description": "Description",
    "excursion.itinerary": "Itinerary",
    "excursion.included": "Included",
    "excursion.what_to_bring": "What to bring",
    "excursion.per_person": "per person",
    "excursion.hours": "hours",
    "excursion.max_capacity": "Max capacity",
    "excursion.people": "people",
    "excursion.difficulty": "Difficulty",
    "excursion.free_cancel": "Free cancellation up to 24h before",
    "excursion.important_info": "Important Information",
    "excursion.confirmation_immediate": "Immediate confirmation",
    "excursion.mobile_ticket": "Mobile ticket",
    "excursion.free_cancellation": "Free cancellation",
    "excursion.pickup_included": "Pickup included",

    // Gallery
    "gallery.badge": "Photo Gallery",
    "gallery.title": "Adventure Gallery",
    "gallery.subtitle": "Discover the most exciting moments from our excursions",

    // About page
    "about.title": "About Us",
    "about.subtitle": "Meet our team",
    "about.description": "We are specialists in creating unique experiences in Tenerife",

    // Contact page
    "contact.title": "Contact",
    "contact.subtitle": "Get in touch with us",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.message": "Message",
    "contact.form.send": "Send",

    // Booking page
    "booking.title": "Booking",
    "booking.subtitle": "Book your adventure",
    "booking.form.date": "Date",
    "booking.form.people": "Number of people",
    "booking.form.excursion": "Excursion",

    // Admin pages
    "admin.title": "Administration",
    "admin.categories": "Category Management",
    "admin.excursions": "Excursion Management",
    "admin.add_category": "Add Category",
    "admin.edit_category": "Edit Category",
    "admin.add_excursion": "Add Excursion",
    "admin.edit_excursion": "Edit Excursion",

    // Form labels
    "form.title": "Title",
    "form.description": "Description",
    "form.price": "Price",
    "form.duration": "Duration",
    "form.capacity": "Capacity",
    "form.difficulty": "Difficulty",
    "form.category": "Category",
    "form.save": "Save",
    "form.cancel": "Cancel",
    "form.delete": "Delete",
    "form.edit": "Edit",

    // Footer
    "footer.company_description": "Specialists in creating unique experiences in Tenerife since 2015",
    "footer.quick_links": "Quick Links",
    "footer.contact_info": "Contact Information",
    "footer.newsletter": "Newsletter",
    "footer.newsletter_text": "Receive special offers and news",
    "footer.subscribe": "Subscribe",
    "footer.copyright": "© 2024 TenerifeParadiseTours. All rights reserved.",
    "footer.designed_by": "Designed by",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms and Conditions",
    "footer.faq": "FAQ",

    // About page - Stats and Story
    "about.hero_badge": "Our Story",
    "about.stat_excursions": "Excursions",
    "about.stat_rating": "Rating",
    "about.achievements": "Our Achievements",
    "about.achievements_subtitle": "Numbers that speak for themselves",
    "about.story_badge": "Our Story",
    "about.story_title": "More than a Decade Creating Memories",
    "about.story_p1":
      "We started in 2015 with a simple mission: to show the true beauty of Tenerife through authentic and memorable experiences.",
    "about.story_p2":
      "Since then, we have guided thousands of visitors through the most spectacular corners of the island, from the peaks of Teide to the volcanic coasts.",
    "about.story_p3":
      "Our team of local guides shares a passion for this unique land, ensuring that each excursion is a window to the Canarian culture and nature.",
    "about.team_caption": "Our team of expert guides",
    "about.team_subtitle": "Passionate about Tenerife",
    "about.pillars_title": "Our Pillars",
    "about.pillars_subtitle": "The values that define us",
    "about.mission": "Mission",
    "about.mission_text":
      "Create authentic tourist experiences that connect our visitors with the essence of Tenerife.",
    "about.vision": "Vision",
    "about.vision_text": "To be the leading company in sustainable and experiential tourism in the Canary Islands.",
    "about.values": "Values",
    "about.values_text":
      "Passion, respect for the environment, quality in service and commitment to the local community.",
    "about.value_passion_title": "Passion for Tenerife",
    "about.value_passion_desc": "Each excursion reflects our deep love for this extraordinary island",
    "about.value_experience_title": "Local Experience",
    "about.value_experience_desc": "More than 10 years sharing the best kept secrets of Tenerife",
    "about.value_security_title": "Guaranteed Security",
    "about.value_security_desc": "Certified security protocols for your total peace of mind",
    "about.value_quality_title": "Premium Quality",
    "about.value_quality_desc": "High quality services with personalized attention in every detail",
    "about.certifications_title": "Certifications and Recognitions",
    "about.certifications_subtitle": "Endorsed by the best institutions",
    "about.cert_sustainable_tourism": "Certified Sustainable Tourism",
    "about.cert_official_guides": "Authorized Official Guides",
    "about.cert_responsible_company": "Responsible Company",
    "about.cert_tripadvisor_excellence": "TripAdvisor Certificate of Excellence",
    "about.cta_title": "Ready to Discover Tenerife?",
    "about.cta_description": "Join thousands of travelers who have already lived unforgettable experiences with us",
    "about.cta_view_excursions": "View Excursions",
    "about.cta_contact": "Contact",

    // Contact page
    "contact.hero_badge": "Direct Contact",
    "contact.hero_subtitle": "Your next adventure starts here",
    "contact.subtitle_extended": "We are here to help you plan the perfect experience in Tenerife",
    "contact.immediate_contact": "Immediate Contact",
    "contact.quick_response_question": "Need a quick answer?",
    "contact.open_whatsapp": "Open WhatsApp",
    "contact.attention_schedule": "Attention Schedule",
    "contact.schedule_text": "Monday to Sunday: 8:00 - 22:00 (Local time)",
    "contact.why_choose_us": "Why choose us?",
    "contact.faq": "FAQ",
    "contact.how_to_book": "How can I book?",
    "contact.how_to_book_answer": "You can book via WhatsApp, phone or through our online form",
    "contact.what_includes": "What do the excursions include?",
    "contact.what_includes_answer": "Transportation, guide, insurance and everything specified in each excursion",
    "contact.group_discounts": "Are there discounts for groups?",
    "contact.group_discounts_answer": "Yes, we offer special discounts for groups of 6 or more people",
    "contact.form_title": "Send us a Message",
    "contact.form_subtitle": "We will respond in less than 2 hours",
    "contact.success_title": "Message Sent!",
    "contact.success_message": "We have received your message and will respond very soon. Thank you for contacting us!",
    "contact.send_another": "Send Another Message",
    "contact.whatsapp_contact": "Contact by WhatsApp",
    "contact.name": "Full name",
    "contact.email": "Email address",
    "contact.phone": "Phone (optional)",
    "contact.message": "Message",
    "contact.send": "Send Message",

    // Contact info
    "contact_info.phone": "Phone",
    "contact_info.whatsapp": "WhatsApp",
    "contact_info.email": "Email",
    "contact_info.location": "Location",
    "contact_info.available": "Available 24/7",
    "contact_info.immediate_response": "Immediate response",
    "contact_info.response_time": "Response in 2 hours",
    "contact_info.canary_islands": "Canary Islands, Spain",

    // Trust indicators
    "trust.guaranteed_response": "Guaranteed Response",
    "trust.guaranteed_text": "We respond in less than 2 hours, always",
    "trust.personal_attention": "Personal Attention",
    "trust.personal_text": "Each client receives personalized and unique treatment",
    "trust.multilingual": "Multilingual",
    "trust.multilingual_text": "We serve in Spanish, English and German",
    "trust.service_passion": "Passion for Service",
    "trust.service_text": "More than 10 years creating unforgettable experiences",

    // Booking page
    "booking.hero_badge": "Easy and Secure Booking",
    "booking.subtitle2": "Your next great adventure is just one message away.",
    "booking.trust_confirmation": "Immediate confirmation",
    "booking.trust_cancellation": "Free cancellation",
    "booking.trust_support": "24/7 Support",
    "booking.form_title": "Booking Form",
    "booking.personal_info": "Personal Information",
    "booking.excursion_details": "Excursion Details",
    "booking.select_excursion": "Select an excursion",
    "booking.excursion_placeholder": "Choose your perfect adventure...",
    "booking.premium_label": "Premium",
    "booking.date": "Preferred date",
    "booking.people": "Number of people",
    "booking.people_count": "person(s)",
    "booking.requests": "Special requests",
    "booking.requests_placeholder": "Any special requests? (diet, mobility, etc.)",
    "booking.submit": "Book via WhatsApp",
    "booking.processing": "Processing...",
    "booking.summary": "Booking Summary",
    "booking.duration_label": "Duration",
    "booking.category_label": "Category",
    "booking.rating_label": "Rating",
    "booking.reviews_label": "reviews",
    "booking.price_per_person": "Price per person",
    "booking.people_summary": "People",
    "booking.total_estimated": "Total Estimated",
    "booking.included_price": "Included in the price",
    "booking.transport": "Transport",
    "booking.guide": "Professional guide",
    "booking.insurance": "Insurance",
    "booking.photos": "Tour photos",
    "booking.select_excursion_message": "Select an excursion to see the summary",
    "booking.select_excursion_subtitle": "Choose your perfect adventure above",
    "booking.why_choose_us": "Why choose us?",
    "booking.trust_guides": "Expert local guides",
    "booking.trust_groups": "Small groups",
    "booking.feature_confirmation": "Immediate Confirmation",
    "booking.feature_confirmation_desc": "Receive instant confirmation via WhatsApp",
    "booking.feature_payment": "Flexible Payment",
    "booking.feature_payment_desc": "Pay in cash on the day of the excursion",
    "booking.feature_experience": "Guaranteed Experience",
    "booking.feature_experience_desc": "More than 4.9/5 stars on all our excursions",
    "booking.whatsapp_greeting": "New booking from the web",
    "booking.whatsapp_excursion": "Excursion",
    "booking.whatsapp_date": "Preferred date",
    "booking.whatsapp_people": "People",
    "booking.whatsapp_price": "Total estimated price",
    "booking.whatsapp_requests": "Special requests",
    "booking.whatsapp_confirm": "We hope to confirm your reservation soon!",
    "booking.success_title": "Booking Sent!",
    "booking.success_message": "We are redirecting you to WhatsApp to confirm your reservation...",
    "booking.error_message": "Error processing the reservation. Please try again.",
    "booking.name_placeholder": "Your full name",
    "booking.email_placeholder": "you@email.com",

    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "Protection of your personal data",
    "privacy.intro.title": "Commitment to your Privacy",
    "privacy.intro.content":
      "At TenerifeParadiseTours we respect and protect the privacy of our users. This policy explains how we collect, use and protect your personal information.",
    "privacy.section1.title": "Information We Collect",
    "privacy.section1.content1": "Contact details: name, email, phone",
    "privacy.section1.content2": "Booking information: dates, preferences, special requests",
    "privacy.section1.content3": "Navigation data: cookies, IP, device used",
    "privacy.section1.content4": "Voluntary information: comments, ratings, photos",
    "privacy.section2.title": "How We Use Your Information",
    "privacy.section2.content1": "Process and confirm your excursion bookings",
    "privacy.section2.content2": "Communicate with you about your booking and services",
    "privacy.section2.content3": "Improve our services and user experience",
    "privacy.section2.content4": "Send special offers (only if you give your consent)",
    "privacy.section3.title": "Data Protection",
    "privacy.section3.content1": "We use SSL encryption to protect your data",
    "privacy.section3.content2": "Limited access only to authorized personnel",
    "privacy.section3.content3": "Secure servers with regular backups",
    "privacy.section3.content4": "Strict compliance with the European GDPR",
    "privacy.section4.title": "Your Rights",
    "privacy.section4.content1": "Access your stored personal data",
    "privacy.section4.content2": "Rectify incorrect or incomplete information",
    "privacy.section4.content3": "Request the deletion of your data",
    "privacy.section4.content4": "Oppose the processing of your data",
    "privacy.section5.title": "Cookies and Technologies",
    "privacy.section5.content1": "Essential cookies for the operation of the site",
    "privacy.section5.content2": "Analytical cookies to improve the experience",
    "privacy.section5.content3": "You can disable cookies in your browser",
    "privacy.section5.content4": "Some functions may be limited without cookies",
    "privacy.section6.title": "Contact and Inquiries",
    "privacy.section6.content1": "For any privacy questions, contact us",
    "privacy.section6.content2": "We will respond within a maximum of 72 hours",
    "privacy.section6.content3": "You have the right to file a complaint with the competent authority",
    "privacy.section6.content4": "We update this policy periodically",
    "privacy.contact_info.title": "Contact Information",
    "privacy.contact_info.company": "Company",
    "privacy.contact_info.company_name": "TenerifeParadiseTours S.L.",
    "privacy.contact_info.cif": "CIF",
    "privacy.contact_info.cif_number": "B-12345678",
    "privacy.contact_info.address": "Address",
    "privacy.contact_info.address_text": "Santa Cruz de Tenerife, Spain",
    "privacy.contact_info.email": "Email",
    "privacy.contact_info.email_address": "Tenerifeparadisetoursandexcursions@hotmail.com",
    "privacy.contact_info.phone": "Phone",
    "privacy.contact_info.phone_number": "+34 617 30 39 29",
    "privacy.buttons.understood": "Understood",
    "privacy.buttons.print": "Print",

    // Terms and Conditions
    "terms.title": "Terms and Conditions",
    "terms.subtitle": "Conditions of use of our services",
    "terms.intro.title": "General Conditions",
    "terms.intro.content":
      "These terms and conditions regulate the use of our tourist services. By making a reservation, you accept these conditions.",
    "terms.section1.title": "Services Offered",
    "terms.section1.content1": "Guided tours of Tenerife with professional guides",
    "terms.section1.content2": "Transportation included from established pick-up points",
    "terms.section1.content3": "Civil liability insurance included",
    "terms.section1.content4": "Necessary material for the activities when applicable",
    "terms.section2.title": "Reservations and Confirmation",
    "terms.section2.content1": "Reservations are confirmed by WhatsApp or email",
    "terms.section2.content2": "Confirmation is required 24 hours before the excursion",
    "terms.section2.content3": "Meeting point and time are communicated upon confirmation",
    "terms.section2.content4": "Date changes subject to availability",
    "terms.section3.title": "Payments and Prices",
    "terms.section3.content1": "Cash payment on the day of the excursion",
    "terms.section3.content2": "Prices include all specified services",
    "terms.section3.content3": "Discounts for groups of 6 or more people",
    "terms.section3.content4": "Prices are subject to change without notice",
    "terms.section4.title": "Cancellations",
    "terms.section4.content1": "Free cancellation up to 24 hours before",
    "terms.section4.content2": "Cancellations due to bad weather: rescheduling or refund",
    "terms.section4.content3": "No-show: no refund",
    "terms.section4.content4": "Last minute cancellations: subject to penalty",
    "terms.section5.title": "Responsibilities",
    "terms.section5.content1": "Participants must follow the guide's instructions",
    "terms.section5.content2": "Report relevant medical conditions",
    "terms.section5.content3": "The company is not responsible for lost items",
    "terms.section5.content4": "Personal medical insurance recommended",
    "terms.section6.title": "Special Conditions",
    "terms.section6.content1": "Minimum and maximum age according to the excursion",
    "terms.section6.content2": "Required level of physical fitness specified",
    "terms.section6.content3": "Weather conditions may affect the route",
    "terms.section6.content4": "Right of admission reserved",
    "terms.important_notice.title": "Important Notice",
    "terms.important_notice.content":
      "These conditions may be modified. The current version is the one published on our website.",
    "terms.legal_info.title": "Legal Information",
    "terms.buttons.accept": "Accept",
    "terms.buttons.print": "Print",

    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Answers to the most common questions",
    "faq.intro.title": "Do you have any questions?",
    "faq.intro.content":
      "Here you will find answers to the most frequently asked questions about our excursions and services.",
    "faq.category1.title": "Reservations and Confirmation",
    "faq.category1.q1.question": "How can I book an excursion?",
    "faq.category1.q1.answer":
      "You can book through WhatsApp, our web form or by calling directly. We will confirm all the details.",
    "faq.category1.q2.question": "When do I receive confirmation?",
    "faq.category1.q2.answer":
      "You will receive immediate confirmation via WhatsApp with all the details: meeting point, time and what to bring.",
    "faq.category1.q3.question": "Can I change the date of my reservation?",
    "faq.category1.q3.answer":
      "Yes, you can change the date without additional cost up to 24 hours before, subject to availability.",
    "faq.category2.title": "Payments and Prices",
    "faq.category2.q1.question": "When should I pay?",
    "faq.category2.q1.answer":
      "Payment is made in cash on the day of the excursion, directly to the guide before starting.",
    "faq.category2.q2.question": "What does the price include?",
    "faq.category2.q2.answer":
      "Includes transportation, professional guide, insurance and everything specified in each excursion. No hidden costs.",
    "faq.category2.q3.question": "Are there discounts for groups?",
    "faq.category2.q3.answer":
      "Yes, we offer special discounts for groups of 6 or more people. Contact us for more details.",
    "faq.category3.title": "During the Excursion",
    "faq.category3.q1.question": "What should I bring?",
    "faq.category3.q1.answer":
      "We will send you a specific list upon confirmation. Generally: water, sunscreen, comfortable shoes and camera.",
    "faq.category3.q2.question": "What happens if it rains?",
    "faq.category3.q2.answer":
      "We monitor the weather constantly. If conditions are not safe, we reschedule or refund.",
    "faq.category3.q3.question": "How many people go per group?",
    "faq.category3.q3.answer":
      "We keep small groups (maximum 8 people) for a more personalized and authentic experience.",
    "faq.category4.title": "Logistics and Transport",
    "faq.category4.q1.question": "Where is the meeting point?",
    "faq.category4.q1.answer":
      "We have several pick-up points. We will assign you the most convenient one according to your location upon confirmation.",
    "faq.category4.q2.question": "Do you pick up at my hotel?",
    "faq.category4.q2.answer": "Yes, we offer pick-up at most hotels in the main tourist areas of Tenerife.",
    "faq.category4.q3.question": "What type of vehicles do you use?",
    "faq.category4.q3.answer":
      "We use comfortable and safe vehicles, adapted to the type of excursion: minibuses, 4x4 or specialized vehicles.",
    "faq.contact.title": "Can't find your answer?",
    "faq.contact.content": "Our team is available to resolve any specific questions you may have.",
    "faq.contact.whatsapp": "Contact by WhatsApp",
    "faq.contact.schedule": "View Schedules",
    "faq.buttons.close": "Close",
    "faq.buttons.print": "Print",
  },
  de: {
    // Navigation
    "nav.home": "Startseite",
    "nav.excursions": "Ausflüge",
    "nav.contact": "Kontakt",
    "nav.about": "Über Uns",
    "nav.booking": "Buchung",
    "nav.language": "Sprache",

    // Hero Section
    "hero.title": "Erleben Sie Teneriffa",
    "hero.subtitle": "auf außergewöhnliche Weise",
    "hero.description": "Bereit für Erlebnisse, die Ihre Sicht auf Teneriffa für immer verändern werden?",
    "hero.description2": "Ihr nächstes großes Abenteuer ist nur eine Nachricht entfernt.",
    "hero.search": "Ausflüge suchen...",
    "hero.stats.excursions": "Ausflüge",
    "hero.stats.rating": "Durchschnittliche Bewertung",
    "hero.stats.satisfaction": "Zufriedenheit",

    // Featured Excursions
    "featured.title": "Abenteuer, die Begeistern",
    "featured.subtitle": "Jedes Erlebnis ist darauf ausgelegt, Erinnerungen zu schaffen, die ein Leben lang halten",
    "featured.book": "Über WhatsApp buchen",
    "featured.from": "Ab",
    "featured.badge": "Bestbewertete Erlebnisse",
    "featured.view_all": "Alle Abenteuer Entdecken",
    "featured.whatsapp_interest": "Hallo! Ich interessiere mich für den Ausflug",
    "featured.whatsapp_info": "Könnten Sie mir weitere Informationen geben?",
    "featured.teide_stars": "Teide & Sterne",
    "featured.whale_watching": "Walbeobachtung",
    "featured.anaga_hiking": "Anaga Wanderung",
    "featured.view_all_short": "Alle Anzeigen",

    // Excursions Page
    "excursions.title": "Alle Unsere",
    "excursions.title2": "Erlebnisse",
    "excursions.subtitle":
      "Entdecken Sie die Magie Teneriffas mit unseren sorgfältig ausgewählten Ausflügen. Von Naturabenteuern bis hin zu einzigartigen gastronomischen Erlebnissen.",
    "excursions.filters": "Filter und Suche",
    "excursions.search_placeholder": "Nach Name oder Beschreibung suchen...",
    "excursions.all_categories": "Alle Kategorien",
    "excursions.all_prices": "Alle Preise",
    "excursions.price_low": "Weniger als €50",
    "excursions.price_medium": "€50 - €80",
    "excursions.price_high": "Mehr als €80",
    "excursions.sort_featured": "Empfohlen",
    "excursions.sort_price_low": "Preis: Niedrig zu Hoch",
    "excursions.sort_price_high": "Preis: Hoch zu Niedrig",
    "excursions.sort_name": "Name A-Z",
    "excursions.found": "Erlebnis Gefunden",
    "excursions.found_plural": "Erlebnisse Gefunden",
    "excursions.showing_all": "Zeige alle unsere verfügbaren Erlebnisse",
    "excursions.filtered_from": "Gefiltert von",
    "excursions.total_experiences": "Gesamterlebnisse",
    "excursions.no_results": "Keine Ausflüge gefunden",
    "excursions.no_results_text":
      "Wir konnten keine Ausflüge finden, die Ihren Filtern entsprechen. Versuchen Sie, Ihre Suchkriterien anzupassen.",
    "excursions.view_all": "Alle Ausflüge anzeigen",
    "excursions.clear_filters": "Alle löschen",
    "excursions.custom_experience": "Finden Sie nicht, was Sie suchen?",
    "excursions.custom_text":
      "Unser Team kann personalisierte Erlebnisse nach Ihren Interessen erstellen. Kontaktieren Sie uns und wir gestalten das perfekte Abenteuer für Sie.",
    "excursions.contact_custom": "Kontakt für Maßgeschneidertes Erlebnis",
    "excursions.search_label": "Suche",

    // Common
    "common.loading": "Laden...",
    "common.error": "Fehler beim Laden der Daten",
    "common.success": "Erfolg",
    "common.duration": "Dauer",
    "common.price": "Preis",
    "common.category": "Kategorie",
    "common.rating": "Bewertung",
    "common.reviews": "Bewertungen",
    "common.free_cancellation": "Kostenlose Stornierung",
    "common.small_group": "Kleine Gruppe",
    "common.all_ratings": "Alle mit 4.8+ Bewertung ⭐",
    "common.preparing": "Ihr Abenteuer wird vorbereitet...",
    "common.loading_experiences": "Erlebnisse werden geladen...",

    // CTA Sections
    "cta.adventure_title": "Beginnen Sie Ihr",
    "cta.adventure_title2": "Perfektes Abenteuer",
    "cta.adventure_text":
      "Beginnen Sie dieses Abenteuer mit uns und entdecken Sie das authentischste Gesicht der Insel",
    "cta.adventure_text2": "Ihre außergewöhnliche Geschichte beginnt mit einem einzigen Klick.",
    "cta.book_now": "Jetzt Buchen",
    "cta.more_info": "Mehr Informationen",
    "cta.ready_title": "Bereit Für Ihr Nächstes Abenteuer?",
    "cta.ready_text":
      "Unser Team wartet darauf, Ihnen zu helfen, unvergessliche Erinnerungen auf Teneriffa zu schaffen. Ihr perfektes Abenteuer ist nur eine Nachricht entfernt!",
    "cta.contact_now": "Jetzt Kontaktieren",
    "cta.view_excursions": "Ausflüge Anzeigen",

    // Categories
    "category.naturaleza": "Natur",
    "category.marina": "Meeresbereich",
    "category.senderismo": "Wandern",
    "category.gastronomia": "Gastronomie",
    "category.paisajes": "Landschaften",
    "category.familia": "Familie",
    "category.aventura": "Abenteuer",
    "category.cultural": "Kulturell",

    // Excursion Details
    "excursion.back_to_excursions": "Zurück zu Ausflügen",
    "excursion.description": "Beschreibung",
    "excursion.itinerary": "Reiseverlauf",
    "excursion.included": "Inbegriffen",
    "excursion.what_to_bring": "Was mitbringen",
    "excursion.per_person": "pro Person",
    "excursion.hours": "Stunden",
    "excursion.max_capacity": "Max. Kapazität",
    "excursion.people": "Personen",
    "excursion.difficulty": "Schwierigkeit",
    "excursion.free_cancel": "Kostenlose Stornierung bis 24h vorher",
    "excursion.important_info": "Wichtige Informationen",
    "excursion.confirmation_immediate": "Sofortige Bestätigung",
    "excursion.mobile_ticket": "Mobile Ticket",
    "excursion.free_cancellation": "Kostenlose Stornierung",
    "excursion.pickup_included": "Abholung inbegriffen",

    // Gallery
    "gallery.badge": "Fotogalerie",
    "gallery.title": "Abenteuer-Galerie",
    "gallery.subtitle": "Entdecken Sie die aufregendsten Momente unserer Ausflüge",

    // About page
    "about.title": "Über Uns",
    "about.subtitle": "Lernen Sie unser Team kennen",
    "about.description": "Wir sind Spezialisten für einzigartige Erlebnisse auf Teneriffa",

    // Contact page
    "contact.title": "Kontakt",
    "contact.subtitle": "Nehmen Sie Kontakt mit uns auf",
    "contact.form.name": "Name",
    "contact.form.email": "E-Mail",
    "contact.form.message": "Nachricht",
    "contact.form.send": "Senden",

    // Booking page
    "booking.title": "Buchung",
    "booking.subtitle": "Buchen Sie Ihr Abenteuer",
    "booking.form.date": "Datum",
    "booking.form.people": "Anzahl Personen",
    "booking.form.excursion": "Ausflug",

    // Admin pages
    "admin.title": "Verwaltung",
    "admin.categories": "Kategorie-Verwaltung",
    "admin.excursions": "Ausflug-Verwaltung",
    "admin.add_category": "Kategorie Hinzufügen",
    "admin.edit_category": "Kategorie Bearbeiten",
    "admin.add_excursion": "Ausflug Hinzufügen",
    "admin.edit_excursion": "Ausflug Bearbeiten",

    // Form labels
    "form.title": "Titel",
    "form.description": "Beschreibung",
    "form.price": "Preis",
    "form.duration": "Dauer",
    "form.capacity": "Kapazität",
    "form.difficulty": "Schwierigkeit",
    "form.category": "Kategorie",
    "form.save": "Speichern",
    "form.cancel": "Abbrechen",
    "form.delete": "Löschen",
    "form.edit": "Bearbeiten",

    // Footer
    "footer.company_description": "Spezialisten für die Schaffung einzigartiger Erlebnisse auf Teneriffa seit 2015",
    "footer.quick_links": "Schnelle Links",
    "footer.contact_info": "Kontaktinformationen",
    "footer.newsletter": "Newsletter",
    "footer.newsletter_text": "Erhalten Sie Sonderangebote und Neuigkeiten",
    "footer.subscribe": "Abonnieren",
    "footer.copyright": "© 2024 TenerifeParadiseTours. Alle Rechte vorbehalten.",
    "footer.designed_by": "Entworfen von",
    "footer.privacy": "Datenschutzbestimmungen",
    "footer.terms": "Allgemeine Geschäftsbedingungen",
    "footer.faq": "FAQ",

    // About page - Stats and Story
    "about.hero_badge": "Unsere Geschichte",
    "about.stat_excursions": "Ausflüge",
    "about.stat_rating": "Bewertung",
    "about.achievements": "Unsere Erfolge",
    "about.achievements_subtitle": "Zahlen, die für sich sprechen",
    "about.story_badge": "Unsere Geschichte",
    "about.story_title": "Mehr als ein Jahrzehnt voller Erinnerungen",
    "about.story_p1":
      "Wir haben 2015 mit einer einfachen Mission begonnen: die wahre Schönheit Teneriffas durch authentische und unvergessliche Erlebnisse zu zeigen.",
    "about.story_p2":
      "Seitdem haben wir Tausende von Besuchern durch die spektakulärsten Ecken der Insel geführt, von den Gipfeln des Teide bis zu den vulkanischen Küsten.",
    "about.story_p3":
      "Unser Team aus lokalen Guides teilt die Leidenschaft für dieses einzigartige Land und stellt sicher, dass jeder Ausflug ein Fenster zur kanarischen Kultur und Natur ist.",
    "about.team_caption": "Unser Team aus erfahrenen Guides",
    "about.team_subtitle": "Leidenschaftlich für Teneriffa",
    "about.pillars_title": "Unsere Säulen",
    "about.pillars_subtitle": "Die Werte, die uns definieren",
    "about.mission": "Mission",
    "about.mission_text":
      "Schaffung authentischer touristischer Erlebnisse, die unsere Besucher mit der Essenz Teneriffas verbinden.",
    "about.vision": "Vision",
    "about.vision_text":
      "Das führende Unternehmen für nachhaltigen und erlebnisorientierten Tourismus auf den Kanarischen Inseln zu sein.",
    "about.values": "Werte",
    "about.values_text":
      "Leidenschaft, Respekt für die Umwelt, Servicequalität und Engagement für die lokale Gemeinschaft.",
    "about.value_passion_title": "Leidenschaft für Teneriffa",
    "about.value_passion_desc": "Jeder Ausflug spiegelt unsere tiefe Liebe zu dieser außergewöhnlichen Insel wider",
    "about.value_experience_title": "Lokale Erfahrung",
    "about.value_experience_desc": "Mehr als 10 Jahre Erfahrung mit den bestgehüteten Geheimnissen Teneriffas",
    "about.value_security_title": "Garantierte Sicherheit",
    "about.value_security_desc": "Zertifizierte Sicherheitsprotokolle für Ihre absolute Sicherheit",
    "about.value_quality_title": "Premium Qualität",
    "about.value_quality_desc": "Hochwertige Dienstleistungen mit persönlicher Betreuung in jedem Detail",
    "about.certifications_title": "Zertifizierungen und Auszeichnungen",
    "about.certifications_subtitle": "Unterstützt von den besten Institutionen",
    "about.cert_sustainable_tourism": "Zertifizierter nachhaltiger Tourismus",
    "about.cert_official_guides": "Autorisierte offizielle Reiseleiter",
    "about.cert_responsible_company": "Verantwortungsbewusstes Unternehmen",
    "about.cert_tripadvisor_excellence": "TripAdvisor-Zertifikat für Exzellenz",
    "about.cta_title": "Bereit, Teneriffa zu entdecken?",
    "about.cta_description":
      "Schließen Sie sich Tausenden von Reisenden an, die bereits unvergessliche Erlebnisse mit uns erlebt haben",
    "about.cta_view_excursions": "Ausflüge ansehen",
    "about.cta_contact": "Kontakt",

    // Contact page
    "contact.hero_badge": "Direkter Kontakt",
    "contact.hero_subtitle": "Ihr nächstes Abenteuer beginnt hier",
    "about.value_security_desc": "Zertifizierte Sicherheitsprotokolle für Ihre absolute Sicherheit",
    "contact.subtitle_extended":
      "Wir sind hier, um Ihnen bei der Planung des perfekten Erlebnisses auf Teneriffa zu helfen",
    "contact.immediate_contact": "Sofortiger Kontakt",
    "contact.quick_response_question": "Benötigen Sie eine schnelle Antwort?",
    "contact.open_whatsapp": "WhatsApp öffnen",
    "contact.attention_schedule": "Betreuungszeiten",
    "contact.schedule_text": "Montag bis Sonntag: 8:00 - 22:00 Uhr (Ortszeit)",
    "contact.why_choose_us": "Warum uns wählen?",
    "contact.faq": "FAQ",
    "contact.how_to_book": "Wie kann ich buchen?",
    "contact.how_to_book_answer": "Sie können über WhatsApp, Telefon oder unser Online-Formular buchen",
    "contact.what_includes": "Was beinhalten die Ausflüge?",
    "contact.what_includes_answer":
      "Transport, Reiseleitung, Versicherung und alles, was in jedem Ausflug angegeben ist",
    "contact.group_discounts": "Gibt es Gruppenrabatte?",
    "contact.group_discounts_answer": "Ja, wir bieten spezielle Rabatte für Gruppen ab 6 Personen an",
    "contact.form_title": "Senden Sie uns eine Nachricht",
    "contact.form_subtitle": "Wir werden Ihnen in weniger als 2 Stunden antworten",
    "contact.success_title": "Nachricht gesendet!",
    "contact.success_message":
      "Wir haben Ihre Nachricht erhalten und werden Ihnen so schnell wie möglich antworten. Vielen Dank für Ihre Kontaktaufnahme!",
    "contact.send_another": "Eine weitere Nachricht senden",
    "contact.whatsapp_contact": "Kontakt per WhatsApp",
    "contact.name": "Vollständiger Name",
    "contact.email": "E-Mail-Adresse",
    "contact.phone": "Telefon (optional)",
    "contact.message": "Nachricht",
    "contact.send": "Nachricht senden",

    // Contact info
    "contact_info.phone": "Telefon",
    "contact_info.whatsapp": "WhatsApp",
    "contact_info.email": "E-Mail",
    "contact_info.location": "Standort",
    "contact_info.available": "Verfügbar 24/7",
    "contact_info.immediate_response": "Sofortige Antwort",
    "contact_info.response_time": "Antwort in 2 Stunden",
    "contact_info.canary_islands": "Kanarische Inseln, Spanien",

    // Trust indicators
    "trust.guaranteed_response": "Garantierte Antwort",
    "trust.guaranteed_text": "Wir antworten immer in weniger als 2 Stunden",
    "trust.personal_attention": "Persönliche Betreuung",
    "trust.personal_text": "Jeder Kunde erhält eine persönliche und einzigartige Betreuung",
    "trust.multilingual": "Mehrsprachig",
    "trust.multilingual_text": "Wir betreuen Sie auf Spanisch, Englisch und Deutsch",
    "trust.service_passion": "Leidenschaft für den Service",
    "trust.service_text": "Mehr als 10 Jahre Erfahrung mit der Schaffung unvergesslicher Erlebnisse",

    // Booking page
    "booking.hero_badge": "Einfache und sichere Buchung",
    "booking.subtitle2": "Ihr nächstes großes Abenteuer ist nur eine Nachricht entfernt.",
    "booking.trust_confirmation": "Sofortige Bestätigung",
    "booking.trust_cancellation": "Kostenlose Stornierung",
    "booking.trust_support": "24/7 Support",
    "booking.form_title": "Buchungsformular",
    "booking.personal_info": "Persönliche Informationen",
    "booking.excursion_details": "Ausflugsdetails",
    "booking.select_excursion": "Wählen Sie einen Ausflug",
    "booking.excursion_placeholder": "Wählen Sie Ihr perfektes Abenteuer...",
    "booking.premium_label": "Premium",
    "booking.date": "Wunschdatum",
    "booking.people": "Anzahl der Personen",
    "booking.people_count": "Person(en)",
    "booking.requests": "Besondere Wünsche",
    "booking.requests_placeholder": "Irgendwelche besonderen Wünsche? (Ernährung, Mobilität usw.)",
    "booking.submit": "Buchen Sie über WhatsApp",
    "booking.processing": "Wird bearbeitet...",
    "booking.summary": "Buchungsübersicht",
    "booking.duration_label": "Dauer",
    "booking.category_label": "Kategorie",
    "booking.rating_label": "Bewertung",
    "booking.reviews_label": "Bewertungen",
    "booking.price_per_person": "Preis pro Person",
    "booking.people_summary": "Personen",
    "booking.total_estimated": "Geschätzter Gesamtpreis",
    "booking.included_price": "Im Preis inbegriffen",
    "booking.transport": "Transport",
    "booking.guide": "Professioneller Reiseleiter",
    "booking.insurance": "Versicherung",
    "booking.photos": "Tourfotos",
    "booking.select_excursion_message": "Wählen Sie einen Ausflug aus, um die Zusammenfassung anzuzeigen",
    "booking.select_excursion_subtitle": "Wählen Sie oben Ihr perfektes Abenteuer aus",
    "booking.why_choose_us": "Warum uns wählen?",
    "booking.trust_guides": "Erfahrene lokale Reiseleiter",
    "booking.trust_groups": "Kleine Gruppen",
    "booking.feature_confirmation": "Sofortige Bestätigung",
    "booking.feature_confirmation_desc": "Erhalten Sie sofortige Bestätigung per WhatsApp",
    "booking.feature_payment": "Flexible Zahlung",
    "booking.feature_payment_desc": "Bezahlen Sie am Tag des Ausflugs in bar",
    "booking.feature_experience": "Garantierte Erfahrung",
    "booking.feature_experience_desc": "Mehr als 4,9/5 Sterne bei allen unseren Ausflügen",
    "booking.whatsapp_greeting": "Neue Buchung von der Website",
    "booking.whatsapp_excursion": "Ausflug",
    "booking.whatsapp_date": "Wunschdatum",
    "booking.whatsapp_people": "Personen",
    "booking.whatsapp_price": "Geschätzter Gesamtpreis",
    "booking.whatsapp_requests": "Besondere Wünsche",
    "booking.whatsapp_confirm": "Wir hoffen, Ihre Buchung bald bestätigen zu können!",
    "booking.success_title": "Buchung gesendet!",
    "booking.success_message": "Wir leiten Sie zu WhatsApp weiter, um Ihre Buchung zu bestätigen...",
    "booking.error_message": "Fehler bei der Bearbeitung der Buchung. Bitte versuchen Sie es erneut.",
    "booking.name_placeholder": "Ihr vollständiger Name",
    "booking.email_placeholder": "you@email.com",

    // Privacy Policy
    "privacy.title": "Datenschutzbestimmungen",
    "privacy.subtitle": "Schutz Ihrer persönlichen Daten",
    "privacy.intro.title": "Verpflichtung zum Schutz Ihrer Daten",
    "privacy.intro.content":
      "Bei TenerifeParadiseTours respektieren und schützen wir die Privatsphäre unserer Nutzer. Diese Richtlinie erläutert, wie wir Ihre persönlichen Daten erfassen, verwenden und schützen.",
    "privacy.section1.title": "Von uns erfasste Informationen",
    "privacy.section1.content1": "Kontaktdaten: Name, E-Mail, Telefon",
    "privacy.section1.content2": "Buchungsinformationen: Daten, Präferenzen, Sonderwünsche",
    "privacy.section1.content3": "Navigationsdaten: Cookies, IP, verwendetes Gerät",
    "privacy.section1.content4": "Freiwillige Informationen: Kommentare, Bewertungen, Fotos",
    "privacy.section2.title": "Wie wir Ihre Informationen verwenden",
    "privacy.section2.content1": "Bearbeitung und Bestätigung Ihrer Ausflugsbuchungen",
    "privacy.section2.content2": "Kommunikation mit Ihnen über Ihre Buchung und Dienstleistungen",
    "privacy.section2.content3": "Verbesserung unserer Dienstleistungen und der Benutzerfreundlichkeit",
    "privacy.section2.content4": "Versenden von Sonderangeboten (nur wenn Sie Ihre Zustimmung geben)",
    "privacy.section3.title": "Datenschutz",
    "privacy.section3.content1": "Wir verwenden SSL-Verschlüsselung, um Ihre Daten zu schützen",
    "privacy.section3.content2": "Beschränkter Zugriff nur für autorisiertes Personal",
    "privacy.section3.content3": "Sichere Server mit regelmäßigen Backups",
    "privacy.section3.content4": "Strikte Einhaltung der europäischen DSGVO",
    "privacy.section4.title": "Ihre Rechte",
    "privacy.section4.content1": "Zugriff auf Ihre gespeicherten persönlichen Daten",
    "privacy.section4.content2": "Berichtigung falscher oder unvollständiger Informationen",
    "privacy.section4.content3": "Antrag auf Löschung Ihrer Daten",
    "privacy.section4.content4": "Widerspruch gegen die Verarbeitung Ihrer Daten",
    "privacy.section5.title": "Cookies und Technologien",
    "privacy.section5.content1": "Essentielle Cookies für den Betrieb der Website",
    "privacy.section5.content2": "Analytische Cookies zur Verbesserung des Erlebnisses",
    "privacy.section5.content3": "Sie können Cookies in Ihrem Browser deaktivieren",
    "privacy.section5.content4": "Einige Funktionen können ohne Cookies eingeschränkt sein",
    "privacy.section6.title": "Kontakt und Anfragen",
    "privacy.section6.content1": "Bei Fragen zum Datenschutz kontaktieren Sie uns",
    "privacy.section6.content2": "Wir werden Ihnen innerhalb von maximal 72 Stunden antworten",
    "privacy.section6.content3": "Sie haben das Recht, eine Beschwerde bei der zuständigen Behörde einzureichen",
    "privacy.section6.content4": "Wir aktualisieren diese Richtlinie regelmäßig",
    "privacy.contact_info.title": "Kontaktinformationen",
    "privacy.contact_info.company": "Unternehmen",
    "privacy.contact_info.company_name": "TenerifeParadiseTours S.L.",
    "privacy.contact_info.cif": "CIF",
    "privacy.contact_info.cif_number": "B-12345678",
    "privacy.contact_info.address": "Adresse",
    "privacy.contact_info.address_text": "Santa Cruz de Tenerife, Spanien",
    "privacy.contact_info.email": "E-Mail",
    "privacy.contact_info.email_address": "Tenerifeparadisetoursandexcursions@hotmail.com",
    "privacy.contact_info.phone": "Telefon",
    "privacy.contact_info.phone_number": "+34 617 30 39 29",
    "privacy.buttons.understood": "Verstanden",
    "privacy.buttons.print": "Drucken",

    // Terms and Conditions
    "terms.title": "Allgemeine Geschäftsbedingungen",
    "terms.subtitle": "Nutzungsbedingungen unserer Dienstleistungen",
    "terms.intro.title": "Allgemeine Bedingungen",
    "terms.intro.content":
      "Diese Allgemeinen Geschäftsbedingungen regeln die Nutzung unserer touristischen Dienstleistungen. Mit einer Buchung akzeptieren Sie diese Bedingungen.",
    "terms.section1.title": "Angebotene Dienstleistungen",
    "terms.section1.content1": "Geführte Ausflüge durch Teneriffa mit professionellen Reiseleitern",
    "terms.section1.content2": "Inklusive Transport von festgelegten Abholpunkten",
    "terms.section1.content3": "Inklusive Haftpflichtversicherung",
    "terms.section1.content4": "Notwendiges Material für die Aktivitäten, falls zutreffend",
    "terms.section2.title": "Reservierungen und Bestätigung",
    "terms.section2.content1": "Reservierungen werden per WhatsApp oder E-Mail bestätigt",
    "terms.section2.content2": "Eine Bestätigung ist 24 Stunden vor dem Ausflug erforderlich",
    "terms.section2.content3": "Treffpunkt und Uhrzeit werden bei der Bestätigung mitgeteilt",
    "terms.section2.content4": "Änderungen des Datums je nach Verfügbarkeit",
    "terms.section3.title": "Zahlungen und Preise",
    "terms.section3.content1": "Barzahlung am Tag des Ausflugs",
    "terms.section3.content2": "Die Preise beinhalten alle angegebenen Leistungen",
    "terms.section3.content3": "Rabatte für Gruppen ab 6 Personen",
    "terms.section3.content4": "Die Preise können sich ohne vorherige Ankündigung ändern",
    "terms.section4.title": "Stornierungen",
    "terms.section4.content1": "Kostenlose Stornierung bis 24 Stunden vorher",
    "terms.section4.content2": "Stornierungen aufgrund von schlechtem Wetter: Umbuchung oder Rückerstattung",
    "terms.section4.content3": "No-Show: keine Rückerstattung",
    "terms.section4.content4": "Stornierungen in letzter Minute: unterliegen einer Strafe",
    "terms.section5.title": "Verantwortlichkeiten",
    "terms.section5.content1": "Die Teilnehmer müssen die Anweisungen des Reiseleiters befolgen",
    "terms.section5.content2": "Mitteilung relevanter medizinischer Bedingungen",
    "terms.section5.content3": "Das Unternehmen ist nicht verantwortlich für verlorene Gegenstände",
    "terms.section5.content4": "Persönliche Krankenversicherung empfohlen",
    "terms.section6.title": "Besondere Bedingungen",
    "terms.section6.content1": "Mindest- und Höchstalter je nach Ausflug",
    "terms.section6.content2": "Erforderliches Maß an körperlicher Fitness angegeben",
    "terms.section6.content3": "Die Wetterbedingungen können die Route beeinträchtigen",
    "terms.section6.content4": "Recht auf Zulassung vorbehalten",
    "terms.important_notice.title": "Wichtiger Hinweis",
    "terms.important_notice.content":
      "Diese Bedingungen können geändert werden. Die aktuelle Version ist die auf unserer Website veröffentlichte.",
    "terms.legal_info.title": "Rechtliche Informationen",
    "terms.buttons.accept": "Akzeptieren",
    "terms.buttons.print": "Drucken",

    // FAQ
    "faq.title": "Häufig gestellte Fragen",
    "faq.subtitle": "Antworten auf die häufigsten Fragen",
    "faq.intro.title": "Haben Sie Fragen?",
    "faq.intro.content":
      "Hier finden Sie Antworten auf die häufigsten Fragen über unsere Ausflüge und Dienstleistungen.",
    "faq.category1.title": "Reservierungen und Bestätigung",
    "faq.category1.q1.question": "Wie kann ich einen Ausflug buchen?",
    "faq.category1.q1.answer":
      "Sie können über WhatsApp, unser Online-Formular oder telefonisch buchen. Wir bestätigen Ihnen alle Details.",
    "faq.category1.q2.question": "Wann erhalte ich die Bestätigung?",
    "faq.category1.q2.answer":
      "Sie erhalten sofort eine Bestätigung per WhatsApp mit allen Details: Treffpunkt, Uhrzeit und was Sie mitbringen müssen.",
    "faq.category1.q3.question": "Kann ich das Datum meiner Buchung ändern?",
    "faq.category1.q3.answer":
      "Ja, Sie können das Datum bis zu 24 Stunden vorher ohne zusätzliche Kosten ändern, je nach Verfügbarkeit.",
    "faq.category2.title": "Zahlungen und Preise",
    "faq.category2.q1.question": "Wann muss ich bezahlen?",
    "faq.category2.q1.answer": "Die Zahlung erfolgt am Tag des Ausflugs in bar, direkt an den Reiseleiter vor Beginn.",
    "faq.category2.q2.question": "Was ist im Preis inbegriffen?",
    "faq.category2.q2.answer":
      "Inbegriffen sind Transport, professioneller Reiseleiter, Versicherung und alles, was in jedem Ausflug angegeben ist. Keine versteckten Kosten.",
    "faq.category2.q3.question": "Gibt es Gruppenrabatte?",
    "faq.category2.q3.answer":
      "Ja, wir bieten spezielle Rabatte für Gruppen ab 6 Personen an. Kontaktieren Sie uns für weitere Details.",
    "faq.category3.title": "Während des Ausflugs",
    "faq.category3.q1.question": "Was soll ich mitbringen?",
    "faq.category3.q1.answer":
      "Wir senden Ihnen nach der Bestätigung eine spezifische Liste. Im Allgemeinen: Wasser, Sonnenschutzmittel, bequeme Schuhe und Kamera.",
    "faq.category3.q2.question": "Was passiert, wenn es regnet?",
    "faq.category3.q2.answer":
      "Wir überwachen das Wetter ständig. Wenn die Bedingungen nicht sicher sind, verschieben wir den Termin oder erstatten den Betrag.",
    "faq.category3.q3.question": "Wie viele Personen sind pro Gruppe?",
    "faq.category3.q3.answer":
      "Wir halten kleine Gruppen (maximal 8 Personen) für ein persönlicheres und authentischeres Erlebnis.",
    "faq.category4.title": "Logistik und Transport",
    "faq.category4.q1.question": "Wo ist der Treffpunkt?",
    "faq.category4.q1.answer":
      "Wir haben mehrere Abholpunkte. Wir weisen Ihnen bei der Bestätigung den für Ihren Standort günstigsten zu.",
    "faq.category4.q2.question": "Holen Sie mich in meinem Hotel ab?",
    "faq.category4.q2.answer":
      "Ja, wir bieten die Abholung in den meisten Hotels in den wichtigsten Touristengebieten Teneriffas an.",
    "faq.category4.q3.question": "Welche Art von Fahrzeugen verwenden Sie?",
    "faq.category4.q3.answer":
      "Wir verwenden komfortable und sichere Fahrzeuge, die an die Art des Ausflugs angepasst sind: Minibusse, 4x4 oder Spezialfahrzeuge.",
    "faq.contact.title": "Sie finden Ihre Antwort nicht?",
    "faq.contact.content":
      "Unser Team steht Ihnen zur Verfügung, um alle spezifischen Fragen zu beantworten, die Sie haben.",
    "faq.contact.whatsapp": "Kontakt per WhatsApp",
    "faq.contact.schedule": "Zeiten anzeigen",
    "faq.buttons.close": "Schließen",
    "faq.buttons.print": "Drucken",
  },
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("es")

  useEffect(() => {
    const storedLanguage = localStorage.getItem("language") as Language | null
    if (storedLanguage && ["es", "en", "de"].includes(storedLanguage)) {
      setLanguage(storedLanguage)
    } else {
      localStorage.setItem("language", "es")
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
